// Generated by OABuilder
package com.remodel.model.oa.propertypath;
 
import com.remodel.model.oa.*;
 
public class DatabaseTypePP {
    private static ColumnTypePPx columnTypes;
    private static DatabasePPx databases;
     

    public static ColumnTypePPx columnTypes() {
        if (columnTypes == null) columnTypes = new ColumnTypePPx(DatabaseType.P_ColumnTypes);
        return columnTypes;
    }

    public static DatabasePPx databases() {
        if (databases == null) databases = new DatabasePPx(DatabaseType.P_Databases);
        return databases;
    }

    public static String id() {
        String s = DatabaseType.P_Id;
        return s;
    }

    public static String created() {
        String s = DatabaseType.P_Created;
        return s;
    }

    public static String name() {
        String s = DatabaseType.P_Name;
        return s;
    }

    public static String description() {
        String s = DatabaseType.P_Description;
        return s;
    }

    public static String driverName() {
        String s = DatabaseType.P_DriverName;
        return s;
    }

    public static String jdbcUrl() {
        String s = DatabaseType.P_JdbcUrl;
        return s;
    }

    public static String type() {
        String s = DatabaseType.P_Type;
        return s;
    }

    public static String pp() {
        return ""; // this
    }
}
 
