// Generated by OABuilder
package com.remodel.model.oa.propertypath;
 
import com.remodel.model.oa.*;
 
public class ForeignTablePP {
    private static ForeignTableColumnPPx foreignTableColumns;
    private static TablePPx table;
    private static TablePPx toTable;
     

    public static ForeignTableColumnPPx foreignTableColumns() {
        if (foreignTableColumns == null) foreignTableColumns = new ForeignTableColumnPPx(ForeignTable.P_ForeignTableColumns);
        return foreignTableColumns;
    }

    public static TablePPx table() {
        if (table == null) table = new TablePPx(ForeignTable.P_Table);
        return table;
    }

    public static TablePPx toTable() {
        if (toTable == null) toTable = new TablePPx(ForeignTable.P_ToTable);
        return toTable;
    }

    public static String id() {
        String s = ForeignTable.P_Id;
        return s;
    }

    public static String created() {
        String s = ForeignTable.P_Created;
        return s;
    }

    public static String fkeyExist() {
        String s = ForeignTable.P_FkeyExist;
        return s;
    }

    public static String pp() {
        return ""; // this
    }
}
 
