// Generated by OABuilder
package com.remodel.model.oa.filter;

import java.util.logging.*;

import com.remodel.model.oa.*;
import com.remodel.model.oa.propertypath.*;
import com.remodel.model.oa.search.*;
import com.remodel.model.search.*;
import com.viaoa.annotation.*;
import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import java.util.*;

@OAClass(useDataSource=false, localOnly=true)
@OAClassFilter(name = "Pkey", displayName = "Pkey", hasInputParams = false, query = "primaryKey = true")
public class ColumnPkeyFilter extends OAObject implements CustomHubFilter<Column> {
    private static final long serialVersionUID = 1L;
    private static Logger LOG = Logger.getLogger(ColumnPkeyFilter.class.getName());

    public static final String PPCode = ":Pkey()";
    private Hub<Column> hubMaster;
    private Hub<Column> hub;
    private HubFilter<Column> hubFilter;
    private OAObjectCacheFilter<Column> cacheFilter;
    private boolean bUseObjectCache;

    public ColumnPkeyFilter() {
        this(null, null, false);
    }
    public ColumnPkeyFilter(Hub<Column> hub) {
        this(null, hub, true);
    }
    public ColumnPkeyFilter(Hub<Column> hubMaster, Hub<Column> hub) {
        this(hubMaster, hub, false);
    }
    public ColumnPkeyFilter(Hub<Column> hubMaster, Hub<Column> hubFiltered, boolean bUseObjectCache) {
        this.hubMaster = hubMaster;
        this.hub = hubFiltered;
        this.bUseObjectCache = bUseObjectCache;
        if (hubMaster != null) getHubFilter();
        if (bUseObjectCache) getObjectCacheFilter();
    }


    public void reset() {
    }

    public boolean isDataEntered() {
        return false;
    }
    public void refresh() {
        if (hubFilter != null) getHubFilter().refresh();
        if (cacheFilter != null) getObjectCacheFilter().refresh();
    }

    @Override
    public HubFilter<Column> getHubFilter() {
        if (hubFilter != null) return hubFilter;
        if (hubMaster == null) return null;
        hubFilter = new HubFilter<Column>(hubMaster, hub) {
            @Override
            public boolean isUsed(Column column) {
                return ColumnPkeyFilter.this.isUsed(column);
            }
        };
        hubFilter.addDependentProperty(ColumnPP.primaryKey(), false);
        hubFilter.refresh();
        return hubFilter;
    }

    public OAObjectCacheFilter<Column> getObjectCacheFilter() {
        if (cacheFilter != null) return cacheFilter;
        if (!bUseObjectCache) return null;
        cacheFilter = new OAObjectCacheFilter<Column>(hub) {
            @Override
            public boolean isUsed(Column column) {
                return ColumnPkeyFilter.this.isUsed(column);
            }
            @Override
            protected void reselect() {
                ColumnPkeyFilter.this.reselect();
            }
        };
        cacheFilter.addDependentProperty(ColumnPP.primaryKey(), false);
        cacheFilter.refresh();
        return cacheFilter;
    }

    public void reselect() {
        // can be overwritten to query datasource
    }

    // ==================
    // this method has custom code that will need to be put into the OABuilder filter

    @Override
    public boolean isUsed(Column column) {
        boolean b = column.getPrimaryKey();
        return b;
    }
}
