// Generated by OABuilder
package com.cdi.model;

import java.util.logging.*;
import com.viaoa.object.*;
import com.viaoa.annotation.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.filter.*;
import com.viaoa.datasource.*;

import com.cdi.model.oa.*;
import com.cdi.model.oa.propertypath.*;
import com.cdi.model.oa.search.*;
import com.cdi.model.oa.filter.*;
import com.cdi.model.search.*;
import com.cdi.model.filter.*;
import com.cdi.delegate.ModelDelegate;
import com.cdi.resource.Resource;

public class SalesOrderStatusModel extends OAObjectModel {
    private static Logger LOG = Logger.getLogger(SalesOrderStatusModel.class.getName());
    
    // Hubs
    protected Hub<SalesOrderStatus> hub;
    // selected salesOrderStatuses
    protected Hub<SalesOrderStatus> hubMultiSelect;
    // detail hubs
    protected Hub<SalesOrder> hubSalesOrders;
    
    // ObjectModels
    protected SalesOrderModel modelSalesOrders;
    
    // SearchModels used for references
    protected SalesOrderSearchModel modelSalesOrdersSearch;
    
    public SalesOrderStatusModel() {
        setDisplayName("Sales Order Status");
        setPluralDisplayName("Sales Order Statuses");
    }
    
    public SalesOrderStatusModel(Hub<SalesOrderStatus> hubSalesOrderStatus) {
        this();
        if (hubSalesOrderStatus != null) HubDelegate.setObjectClass(hubSalesOrderStatus, SalesOrderStatus.class);
        this.hub = hubSalesOrderStatus;
    }
    public SalesOrderStatusModel(SalesOrderStatus salesOrderStatus) {
        this();
        getHub().add(salesOrderStatus);
        getHub().setPos(0);
    }
    
    public Hub<SalesOrderStatus> getOriginalHub() {
        return getHub();
    }
    
    public Hub<SalesOrder> getSalesOrders() {
        // createMethod=false, used by getSalesOrdersSearchModel() for searches
        if (hubSalesOrders != null) return hubSalesOrders;
        hubSalesOrders = new Hub<SalesOrder>(SalesOrder.class);
        hubSalesOrders.setSelectWhereHub(getHub(), SalesOrderStatus.P_SalesOrders);
        getHub().onChangeAO(hubEvent -> hubSalesOrders.clear());
        return hubSalesOrders;
    }
    public SalesOrderStatus getSalesOrderStatus() {
        return getHub().getAO();
    }
    
    public Hub<SalesOrderStatus> getHub() {
        if (hub == null) {
            hub = new Hub<SalesOrderStatus>(SalesOrderStatus.class);
        }
        return hub;
    }
    
    public Hub<SalesOrderStatus> getMultiSelectHub() {
        if (hubMultiSelect == null) {
            hubMultiSelect = new Hub<SalesOrderStatus>(SalesOrderStatus.class);
        }
        return hubMultiSelect;
    }
    
    public SalesOrderModel getSalesOrdersModel() {
        if (modelSalesOrders != null) return modelSalesOrders;
        modelSalesOrders = new SalesOrderModel(getSalesOrders());
        modelSalesOrders.setDisplayName("Sales Order");
        modelSalesOrders.setPluralDisplayName("Sales Orders");
        modelSalesOrders.setForJfc(getForJfc());
        modelSalesOrders.setAllowNew(false);
        modelSalesOrders.setAllowSave(true);
        modelSalesOrders.setAllowAdd(false);
        modelSalesOrders.setAllowMove(false);
        modelSalesOrders.setAllowRemove(false);
        modelSalesOrders.setAllowDelete(false);
        modelSalesOrders.setAllowRefresh(false);
        modelSalesOrders.setAllowSearch(true);
        modelSalesOrders.setAllowHubSearch(false);
        modelSalesOrders.setAllowDownload(true);
        modelSalesOrders.setAllowGotoEdit(true);
        modelSalesOrders.setViewOnly(getViewOnly());
        modelSalesOrders.setAllowTableFilter(true);
        modelSalesOrders.setAllowTableSorting(true);
        modelSalesOrders.setAllowMultiSelect(false);
        modelSalesOrders.setAllowCopy(false);
        modelSalesOrders.setAllowCut(false);
        modelSalesOrders.setAllowPaste(false);
        // call SalesOrderStatus.salesOrdersModelCallback(SalesOrderModel) to be able to customize this model
        OAObjectCallbackDelegate.onObjectCallbackModel(SalesOrderStatus.class, SalesOrderStatus.P_SalesOrders, modelSalesOrders);
    
        return modelSalesOrders;
    }
    
    public SalesOrderSearchModel getSalesOrdersSearchModel() {
        if (modelSalesOrdersSearch != null) return modelSalesOrdersSearch;
        modelSalesOrdersSearch = new SalesOrderSearchModel(getSalesOrders()); // createMethod=false, directly uses hub
        return modelSalesOrdersSearch;
    }
    
    public HubCopy<SalesOrderStatus> createHubCopy() {
        Hub<SalesOrderStatus> hubSalesOrderStatusx = new Hub<>(SalesOrderStatus.class);
        HubCopy<SalesOrderStatus> hc = new HubCopy<>(getHub(), hubSalesOrderStatusx, true);
        return hc;
    }
    public SalesOrderStatusModel createCopy() {
        SalesOrderStatusModel mod = new SalesOrderStatusModel(createHubCopy().getHub());
        return mod;
    }
}

