// Generated by OABuilder
package com.oreillyauto.remodel.model.oa.propertypath;
 
import com.oreillyauto.remodel.model.oa.*;
 
public class ColumnTypePP {
    private static DataTypePPx calcDataType;
    private static ColumnPPx columns;
    private static DatabaseTypePPx databaseType;
    private static DataTypePPx dataType;
    private static SqlTypePPx sqlType;
     

    public static DataTypePPx calcDataType() {
        if (calcDataType == null) calcDataType = new DataTypePPx(ColumnType.P_CalcDataType);
        return calcDataType;
    }

    public static ColumnPPx columns() {
        if (columns == null) columns = new ColumnPPx(ColumnType.P_Columns);
        return columns;
    }

    public static DatabaseTypePPx databaseType() {
        if (databaseType == null) databaseType = new DatabaseTypePPx(ColumnType.P_DatabaseType);
        return databaseType;
    }

    public static DataTypePPx dataType() {
        if (dataType == null) dataType = new DataTypePPx(ColumnType.P_DataType);
        return dataType;
    }

    public static SqlTypePPx sqlType() {
        if (sqlType == null) sqlType = new SqlTypePPx(ColumnType.P_SqlType);
        return sqlType;
    }

    public static String id() {
        String s = ColumnType.P_Id;
        return s;
    }

    public static String created() {
        String s = ColumnType.P_Created;
        return s;
    }

    public static String isJsonb() {
        String s = ColumnType.P_IsJsonb;
        return s;
    }

    public static String seq() {
        String s = ColumnType.P_Seq;
        return s;
    }

    public static String display() {
        String s = ColumnType.P_Display;
        return s;
    }
}
 
