// Generated by OABuilder
package com.oreillyauto.remodel.model.oa.propertypath;
 
import com.oreillyauto.remodel.model.oa.*;
 
public class JavaTypePP {
    private static DataTypePPx dataType;
    private static JsonColumnPPx jsonColumns;
     

    public static DataTypePPx dataType() {
        if (dataType == null) dataType = new DataTypePPx(JavaType.P_DataType);
        return dataType;
    }

    public static JsonColumnPPx jsonColumns() {
        if (jsonColumns == null) jsonColumns = new JsonColumnPPx(JavaType.P_JsonColumns);
        return jsonColumns;
    }

    public static String id() {
        String s = JavaType.P_Id;
        return s;
    }

    public static String created() {
        String s = JavaType.P_Created;
        return s;
    }

    public static String name() {
        String s = JavaType.P_Name;
        return s;
    }

    public static String seq() {
        String s = JavaType.P_Seq;
        return s;
    }

    public static String pp() {
        return ""; // this
    }
}
 
