// Generated by OABuilder
package com.oreillyauto.remodel.model.oa.propertypath;
 
import java.io.Serializable;

import com.oreillyauto.remodel.model.oa.*;
 
public class JsonObjectPPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
     
    public JsonObjectPPx(String name) {
        this(null, name);
    }

    public JsonObjectPPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null && name.length() > 0) {
            if (s.length() > 0 && name.charAt(0) != ':') s += ".";
            s += name;
        }
        pp = s;
    }

    public ColumnPPx column() {
        ColumnPPx ppx = new ColumnPPx(this, JsonObject.P_Column);
        return ppx;
    }

    public JsonColumnPPx jsonColumns() {
        JsonColumnPPx ppx = new JsonColumnPPx(this, JsonObject.P_JsonColumns);
        return ppx;
    }

    public JsonObjectPPx jsonObjects() {
        JsonObjectPPx ppx = new JsonObjectPPx(this, JsonObject.P_JsonObjects);
        return ppx;
    }

    public JsonObjectPPx parentJsonObject() {
        JsonObjectPPx ppx = new JsonObjectPPx(this, JsonObject.P_ParentJsonObject);
        return ppx;
    }

    public String id() {
        return pp + "." + JsonObject.P_Id;
    }

    public String created() {
        return pp + "." + JsonObject.P_Created;
    }

    public String name() {
        return pp + "." + JsonObject.P_Name;
    }

    public String type() {
        return pp + "." + JsonObject.P_Type;
    }

    public String fileName() {
        return pp + "." + JsonObject.P_FileName;
    }

    public String packageName() {
        return pp + "." + JsonObject.P_PackageName;
    }

    public String matchValue() {
        return pp + "." + JsonObject.P_MatchValue;
    }

    public String parse() {
        return pp + ".parse";
    }

    @Override
    public String toString() {
        return pp;
    }
    public String pp() {
        return pp;
    }
}
 
