// Generated by OABuilder
package com.cdi.model.oa.propertypath;
 
import java.io.Serializable;
import com.cdi.model.oa.*;
 
public class ChatSessionPPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
     
    public ChatSessionPPx(String name) {
        this(null, name);
    }

    public ChatSessionPPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null && name.length() > 0) {
            if (s.length() > 0 && name.charAt(0) != ':') s += ".";
            s += name;
        }
        pp = s;
    }

    public ChatMessagePPx calcLastChatMessage() {
        ChatMessagePPx ppx = new ChatMessagePPx(this, ChatSession.P_CalcLastChatMessage);
        return ppx;
    }

    public ChatMessagePPx chatMessages() {
        ChatMessagePPx ppx = new ChatMessagePPx(this, ChatSession.P_ChatMessages);
        return ppx;
    }

    public UserPPx users() {
        UserPPx ppx = new UserPPx(this, ChatSession.P_Users);
        return ppx;
    }

    public String id() {
        return pp + "." + ChatSession.P_Id;
    }

    public String created() {
        return pp + "." + ChatSession.P_Created;
    }

    public String name() {
        return pp + "." + ChatSession.P_Name;
    }

    public String inactive() {
        return pp + "." + ChatSession.P_Inactive;
    }

    public String allFlag() {
        return pp + "." + ChatSession.P_AllFlag;
    }

    @Override
    public String toString() {
        return pp;
    }
    public String pp() {
        return pp;
    }
}
 
