// Generated by OABuilder
package com.cdi.model.oa.propertypath;
 
import com.cdi.model.oa.*;
 
public class PalletPP {
    private static WorkOrderPalletPPx workOrderPallets;
     

    public static WorkOrderPalletPPx workOrderPallets() {
        if (workOrderPallets == null) workOrderPallets = new WorkOrderPalletPPx(Pallet.P_WorkOrderPallets);
        return workOrderPallets;
    }

    public static String id() {
        String s = Pallet.P_Id;
        return s;
    }

    public static String code() {
        String s = Pallet.P_Code;
        return s;
    }

    public static String name() {
        String s = Pallet.P_Name;
        return s;
    }

    public static String seq() {
        String s = Pallet.P_Seq;
        return s;
    }
}
 
