// Generated by OABuilder
package com.cdi.model.oa.propertypath;
 
import java.io.Serializable;
import com.cdi.model.oa.*;
 
public class PriceCodePPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
     
    public PriceCodePPx(String name) {
        this(null, name);
    }

    public PriceCodePPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null && name.length() > 0) {
            if (s.length() > 0 && name.charAt(0) != ':') s += ".";
            s += name;
        }
        pp = s;
    }

    public ItemQuotePPx itemQuotes() {
        ItemQuotePPx ppx = new ItemQuotePPx(this, PriceCode.P_ItemQuotes);
        return ppx;
    }

    public SalesOrderPPx salesOrders() {
        SalesOrderPPx ppx = new SalesOrderPPx(this, PriceCode.P_SalesOrders);
        return ppx;
    }

    public String id() {
        return pp + "." + PriceCode.P_Id;
    }

    public String name() {
        return pp + "." + PriceCode.P_Name;
    }

    public String rate() {
        return pp + "." + PriceCode.P_Rate;
    }

    public String itemCode() {
        return pp + "." + PriceCode.P_ItemCode;
    }

    public String color() {
        return pp + "." + PriceCode.P_Color;
    }

    public String texture() {
        return pp + "." + PriceCode.P_Texture;
    }

    public String seq() {
        return pp + "." + PriceCode.P_Seq;
    }

    @Override
    public String toString() {
        return pp;
    }
    public String pp() {
        return pp;
    }
}
 
