// Generated by OABuilder
package com.cdi.model.oa.propertypath;
 
import java.io.Serializable;
import com.cdi.model.oa.*;
 
public class SalesOrderStatusPPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
     
    public SalesOrderStatusPPx(String name) {
        this(null, name);
    }

    public SalesOrderStatusPPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null && name.length() > 0) {
            if (s.length() > 0 && name.charAt(0) != ':') s += ".";
            s += name;
        }
        pp = s;
    }

    public SalesOrderPPx salesOrders() {
        SalesOrderPPx ppx = new SalesOrderPPx(this, SalesOrderStatus.P_SalesOrders);
        return ppx;
    }

    public String id() {
        return pp + "." + SalesOrderStatus.P_Id;
    }

    public String name() {
        return pp + "." + SalesOrderStatus.P_Name;
    }

    public String description() {
        return pp + "." + SalesOrderStatus.P_Description;
    }

    @Override
    public String toString() {
        return pp;
    }
    public String pp() {
        return pp;
    }
}
 
