// Generated by OABuilder
package com.cdi.model.oa.propertypath;
 
import java.io.Serializable;
import com.cdi.model.oa.*;
 
public class SalesOrderItemPPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
     
    public SalesOrderItemPPx(String name) {
        this(null, name);
    }

    public SalesOrderItemPPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null && name.length() > 0) {
            if (s.length() > 0 && name.charAt(0) != ':') s += ".";
            s += name;
        }
        pp = s;
    }

    public ItemPPx item() {
        ItemPPx ppx = new ItemPPx(this, SalesOrderItem.P_Item);
        return ppx;
    }

    public ItemAddOnPPx itemAddOns() {
        ItemAddOnPPx ppx = new ItemAddOnPPx(this, SalesOrderItem.P_ItemAddOns);
        return ppx;
    }

    public SalesOrderPPx salesOrder() {
        SalesOrderPPx ppx = new SalesOrderPPx(this, SalesOrderItem.P_SalesOrder);
        return ppx;
    }

    public ServiceCodePPx serviceCode() {
        ServiceCodePPx ppx = new ServiceCodePPx(this, SalesOrderItem.P_ServiceCode);
        return ppx;
    }

    public String id() {
        return pp + "." + SalesOrderItem.P_Id;
    }

    public String seq() {
        return pp + "." + SalesOrderItem.P_Seq;
    }

    public String location() {
        return pp + "." + SalesOrderItem.P_Location;
    }

    public String customItem() {
        return pp + "." + SalesOrderItem.P_CustomItem;
    }

    public String itemDescription() {
        return pp + "." + SalesOrderItem.P_ItemDescription;
    }

    public String quantity() {
        return pp + "." + SalesOrderItem.P_Quantity;
    }

    public String unitPrice() {
        return pp + "." + SalesOrderItem.P_UnitPrice;
    }

    public String unitWeight() {
        return pp + "." + SalesOrderItem.P_UnitWeight;
    }

    public String servicePrice() {
        return pp + "." + SalesOrderItem.P_ServicePrice;
    }

    public String addOnPrice() {
        return pp + "." + SalesOrderItem.P_AddOnPrice;
    }

    public String note() {
        return pp + "." + SalesOrderItem.P_Note;
    }

    public String showSubTotal() {
        return pp + "." + SalesOrderItem.P_ShowSubTotal;
    }

    public String fakeUnitPrice() {
        return pp + "." + SalesOrderItem.P_FakeUnitPrice;
    }

    public String sellRate() {
        return pp + "." + SalesOrderItem.P_SellRate;
    }

    public String totalItemOurPrice() {
        return pp + "." + SalesOrderItem.P_TotalItemOurPrice;
    }

    public String itemSellPrice() {
        return pp + "." + SalesOrderItem.P_ItemSellPrice;
    }

    public String totalItemSellPrice() {
        return pp + "." + SalesOrderItem.P_TotalItemSellPrice;
    }

    public String totalSellPrice() {
        return pp + "." + SalesOrderItem.P_TotalSellPrice;
    }

    public String totalWeight() {
        return pp + "." + SalesOrderItem.P_TotalWeight;
    }

    public String allowsItemAddOn() {
        return pp + "." + SalesOrderItem.P_AllowsItemAddOn;
    }

    public String assignSameItemAddOn() {
        return pp + ".assignSameItemAddOn";
    }

    @Override
    public String toString() {
        return pp;
    }
    public String pp() {
        return pp;
    }
}
 
