// Generated by OABuilder
package com.cdi.model.oa.propertypath;
 
import java.io.Serializable;
import com.cdi.model.oa.*;
 
public class TexturePPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
     
    public TexturePPx(String name) {
        this(null, name);
    }

    public TexturePPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null && name.length() > 0) {
            if (s.length() > 0 && name.charAt(0) != ':') s += ".";
            s += name;
        }
        pp = s;
    }

    public OrderPPx orders() {
        OrderPPx ppx = new OrderPPx(this, Texture.P_Orders);
        return ppx;
    }

    public String id() {
        return pp + "." + Texture.P_Id;
    }

    public String code() {
        return pp + "." + Texture.P_Code;
    }

    public String name() {
        return pp + "." + Texture.P_Name;
    }

    public String image() {
        return pp + "." + Texture.P_Image;
    }

    public String seq() {
        return pp + "." + Texture.P_Seq;
    }

    public String codeName() {
        return pp + "." + Texture.P_CodeName;
    }

    @Override
    public String toString() {
        return pp;
    }
    public String pp() {
        return pp;
    }
}
 
