// Generated by OABuilder
package test.xice.tsac.model.oa;
 
import java.sql.*;
import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.lang.OAString;
import com.viaoa.util.*;
import com.viaoa.annotation.*;
import com.viaoa.datetime.OADateTime;

import test.hifive.model.oa.ServerInfo.Status;
import test.xice.tsac.model.delegate.OAObjectInfoDelegate;
import test.xice.tsac.model.oa.filter.*;
import test.xice.tsac.model.oa.propertypath.*;
 
@OAClass(
    shortName = "war",
    displayName = "Warning",
    displayProperty = "created"
)
@OATable(
)
public class Warning extends OAObject {
    private static final long serialVersionUID = 1L;
    public static final String PROPERTY_Id = "Id";
    public static final String P_Id = "Id";
    public static final String PROPERTY_Created = "Created";
    public static final String P_Created = "Created";
    public static final String PROPERTY_Message = "Message";
    public static final String P_Message = "Message";
    public static final String PROPERTY_ExceptionMessage = "ExceptionMessage";
    public static final String P_ExceptionMessage = "ExceptionMessage";
    public static final String PROPERTY_StackTrace = "StackTrace";
    public static final String P_StackTrace = "StackTrace";
    public static final String PROPERTY_ActionComment = "ActionComment";
    public static final String P_ActionComment = "ActionComment";
     
     
    public static final String PROPERTY_GSMRWarning = "GSMRWarning";
    public static final String P_GSMRWarning = "GSMRWarning";
     
    protected int id;
    protected OADateTime created;
    protected String message;
    protected String exceptionMessage;
    protected String stackTrace;
    
    public static final String P_Status = "status";
    public static final String P_StatusString = "statusString";
    public static final String P_StatusEnum = "statusEnum";
    public static final String P_StatusDisplay = "statusDisplay";
    protected volatile int status;
    public static final int STATUS_Starting = 0;
    public static final int STATUS_Running = 1;
    public static final int STATUS_Stopping = 2;
    public static final int STATUS_Stopped = 3;
    public static enum Status {
    	Starting("Starting"),
    	Running("Running"),
    	Stopping("Stopping"),
    	Stopped("Stopped");

        private String display;
        Status(String display) {
            this.display = display;
        }

        public String getDisplay() {
            return display;
        }
    }
    @OAProperty(displayLength = 14, isProcessed = true)
    @OAColumn(sqlType = java.sql.Types.INTEGER)
    public int getStatus() {
        return status;
    }
    public void setStatus(int newValue) {
        int old = status;
        fireBeforePropertyChange(P_Status, old, newValue);
        this.status = newValue;
        firePropertyChange(P_Status, old, this.status);
    }
    @OAProperty(enumPropertyName = P_Status)
    public String getStatusString() {
        Status status = getStatusEnum();
        if (status == null) return null;
        return status.name();
    }
    public void setStatusString(String val) {
        int x = -1;
        if (OAString.isNotEmpty(val)) {
            Status status = Status.valueOf(val);
            if (status != null) x = status.ordinal();
        }
        if (x < 0) setNull(P_Status);
        else setStatus(x);
    }
    @OAProperty(enumPropertyName = P_Status)
    public Status getStatusEnum() {
        if (isNull(P_Status)) return null;
        final int val = getStatus();
        if (val < 0 || val >= Status.values().length) return null;
        return Status.values()[val];
    }
    public void setStatusEnum(Status val) {
        if (val == null) {
            setNull(P_Status);
        }
        else {
            setStatus(val.ordinal());
        }
    }
    @OACalculatedProperty(enumPropertyName = P_Status, displayName = "Status", displayLength = 14, columnLength = 6, properties = {P_Status} )
    public String getStatusDisplay() {
        Status status = getStatusEnum();
        if (status == null) return null;
        return status.getDisplay();
    }
    
    
    public static final String P_ActionTaken = "actionTaken";
    public static final String P_ActionTakenString = "actionTakenString";
    public static final String P_ActionTakenEnum = "actionTakenEnum";
    public static final String P_ActionTakenDisplay = "actionTakenDisplay";
    protected volatile int actionTaken;

    public static final int ACTIONTAKEN_OPEN = 0;
    public static final int ACTIONTAKEN_LOOKING = 1;
    public static final int ACTIONTAKEN_IGNORE = 2;
    public static final int ACTIONTAKEN_RESOLVED = 3;
    public static final int ACTIONTAKEN_KNOWNISSUE = 4;
    public static enum ActionTaken {
    	OPEN("OPEN"),
    	LOOKING("LOOKING"),
    	IGNORE("IGNORE"),
    	RESOLVED("RESOLVED"),
    	Stopped("KNOWNISSUE");

        private String display;
        ActionTaken(String display) {
            this.display = display;
        }

        public String getDisplay() {
            return display;
        }
    }
    @OAProperty(displayName = "Action Taken", displayLength = 5, isNameValue = true)
    @OAColumn(sqlType = java.sql.Types.INTEGER)
    public int getActionTaken() {
        return actionTaken;
    }
    public void setActionTaken(int newValue) {
        int old = actionTaken;
        fireBeforePropertyChange(P_ActionTaken, old, newValue);
        this.actionTaken = newValue;
        firePropertyChange(P_ActionTaken, old, this.actionTaken);
    }
    @OAProperty(enumPropertyName = P_ActionTaken)
    public String getActionTakenString() {
        ActionTaken actionTaken = getActionTakenEnum();
        if (actionTaken == null) return null;
        return actionTaken.name();
    }
    public void setActionTakenString(String val) {
        int x = -1;
        if (OAString.isNotEmpty(val)) {
            ActionTaken actionTaken = ActionTaken.valueOf(val);
            if (actionTaken != null) x = actionTaken.ordinal();
        }
        if (x < 0) setNull(P_ActionTaken);
        else setActionTaken(x);
    }
    @OAProperty(enumPropertyName = P_ActionTaken)
    public ActionTaken getActionTakenEnum() {
        if (isNull(P_ActionTaken)) return null;
        final int val = getActionTaken();
        if (val < 0 || val >= ActionTaken.values().length) return null;
        return ActionTaken.values()[val];
    }
    public void setActionTakenEnum(ActionTaken val) {
        if (val == null) {
            setNull(P_ActionTaken);
        }
        else {
            setActionTaken(val.ordinal());
        }
    }
    @OACalculatedProperty(enumPropertyName = P_ActionTaken, displayName = "ActionTaken", displayLength = 14, columnLength = 6, properties = {P_ActionTaken} )
    public String getActionTakenDisplay() {
        ActionTaken actionTaken = getActionTakenEnum();
        if (actionTaken == null) return null;
        return actionTaken.getDisplay();
    }
    

    
    protected String actionComment;
     
    // Links to other objects.
     
    public Warning() {
        if (!isLoading()) {
            setCreated(new OADateTime());
        }
    }
     
    public Warning(int id) {
        this();
        setId(id);
    }
     
    @OAProperty(isUnique = true, displayLength = 5, isProcessed = true)
    @OAId()
    @OAColumn(sqlType = java.sql.Types.INTEGER)
    public int getId() {
        return id;
    }
    
    public void setId(int newValue) {
        fireBeforePropertyChange(P_Id, this.id, newValue);
        int old = id;
        this.id = newValue;
        firePropertyChange(P_Id, old, this.id);
    }
    @OAProperty(defaultValue = "new OADateTime()", displayLength = 15, isProcessed = true)
    @OAColumn(sqlType = java.sql.Types.TIMESTAMP)
    public OADateTime getCreated() {
        return created;
    }
    
    public void setCreated(OADateTime newValue) {
        fireBeforePropertyChange(P_Created, this.created, newValue);
        OADateTime old = created;
        this.created = newValue;
        firePropertyChange(P_Created, old, this.created);
    }
    @OAProperty(maxLength = 254, displayLength = 25, columnLength = 18, isProcessed = true)
    @OAColumn(maxLength = 254)
    public String getMessage() {
        return message;
    }
    
    public void setMessage(String newValue) {
        fireBeforePropertyChange(P_Message, this.message, newValue);
        String old = message;
        this.message = newValue;
        firePropertyChange(P_Message, old, this.message);
    }
    @OAProperty(displayName = "Exception Message", maxLength = 254, displayLength = 25, columnLength = 18, isProcessed = true)
    @OAColumn(maxLength = 254)
    public String getExceptionMessage() {
        return exceptionMessage;
    }
    
    public void setExceptionMessage(String newValue) {
        fireBeforePropertyChange(P_ExceptionMessage, this.exceptionMessage, newValue);
        String old = exceptionMessage;
        this.exceptionMessage = newValue;
        firePropertyChange(P_ExceptionMessage, old, this.exceptionMessage);
    }
    @OAProperty(displayName = "Stack Trace", maxLength = 10, displayLength = 10, isProcessed = true)
    @OAColumn(sqlType = java.sql.Types.CLOB)
    public String getStackTrace() {
        return stackTrace;
    }
    
    public void setStackTrace(String newValue) {
        fireBeforePropertyChange(P_StackTrace, this.stackTrace, newValue);
        String old = stackTrace;
        this.stackTrace = newValue;
        firePropertyChange(P_StackTrace, old, this.stackTrace);
    }
    @OAProperty(displayName = "Action Comment", maxLength = 13, displayLength = 13)
    @OAColumn(sqlType = java.sql.Types.CLOB)
    public String getActionComment() {
        return actionComment;
    }
    
    public void setActionComment(String newValue) {
        fireBeforePropertyChange(P_ActionComment, this.actionComment, newValue);
        String old = actionComment;
        this.actionComment = newValue;
        firePropertyChange(P_ActionComment, old, this.actionComment);
    }
    @OAOne(
        reverseName = GSMRWarning.P_Warning, 
        allowCreateNew = false, 
        allowAddExisting = false, 
        mustBeEmptyForDelete = true
    )
    private GSMRWarning getGSMRWarning() {
        // oamodel has createMethod set to false, this method exists only for annotations.
        return null;
    }
    
    public void load(ResultSet rs, int id) throws SQLException {
        this.id = id;
        java.sql.Timestamp timestamp;
        timestamp = rs.getTimestamp(2);
        if (timestamp != null) this.created = new OADateTime(timestamp);
        this.message = rs.getString(3);
        this.exceptionMessage = rs.getString(4);
        this.stackTrace = rs.getString(5);
        this.actionTaken = (int) rs.getInt(6);
        if (rs.wasNull()) {
            OAObjectInfoDelegate.setPrimitiveNull(this, Warning.P_ActionTaken, true);
        }
        this.actionComment = rs.getString(7);
        if (rs.getMetaData().getColumnCount() != 7) {
            throw new SQLException("invalid number of columns for load method");
        }

        changedFlag = false;
        newFlag = false;
    }
}
 
