// Generated by OABuilder
package com.corptostore.model.oa.propertypath;
 
import java.io.Serializable;

import com.corptostore.model.oa.*;
import com.corptostore.model.oa.StatusInfoMessage;
import com.corptostore.model.oa.propertypath.PPxInterface;
import com.corptostore.model.oa.propertypath.StatusInfoPPx;
 
public class StatusInfoMessagePPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
     
    public StatusInfoMessagePPx(String name) {
        this(null, name);
    }

    public StatusInfoMessagePPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null && name.length() > 0) {
            if (s.length() > 0 && name.charAt(0) != ':') s += ".";
            s += name;
        }
        pp = s;
    }

    public StatusInfoPPx statusInfo() {
        StatusInfoPPx ppx = new StatusInfoPPx(this, StatusInfoMessage.P_StatusInfo);
        return ppx;
    }

    public StatusInfoPPx statusInfoActivity() {
        StatusInfoPPx ppx = new StatusInfoPPx(this, StatusInfoMessage.P_StatusInfoActivity);
        return ppx;
    }

    public StatusInfoPPx statusInfoAlert() {
        StatusInfoPPx ppx = new StatusInfoPPx(this, StatusInfoMessage.P_StatusInfoAlert);
        return ppx;
    }

    public String id() {
        return pp + "." + StatusInfoMessage.P_Id;
    }

    public String created() {
        return pp + "." + StatusInfoMessage.P_Created;
    }

    public String type() {
        return pp + "." + StatusInfoMessage.P_Type;
    }

    public String message() {
        return pp + "." + StatusInfoMessage.P_Message;
    }

    public String counter() {
        return pp + "." + StatusInfoMessage.P_Counter;
    }

    public String exception() {
        return pp + "." + StatusInfoMessage.P_Exception;
    }

    @Override
    public String toString() {
        return pp;
    }
    public String pp() {
        return pp;
    }
}
 
