// Generated by OABuilder
package com.corptostore.model.oa.propertypath;
 
import com.corptostore.model.oa.*;
import com.corptostore.model.oa.StoreTransmitBatch;
import com.corptostore.model.oa.propertypath.StoreBatchPPx;
import com.corptostore.model.oa.propertypath.StorePPx;
import com.corptostore.model.oa.propertypath.StoreTransmitInfoPPx;
import com.corptostore.model.oa.propertypath.TransmitBatchPPx;
 
public class StoreTransmitBatchPP {
    private static StorePPx store;
    private static StoreBatchPPx storeBatches;
    private static StoreTransmitInfoPPx storeTransmitInfos;
    private static TransmitBatchPPx transmitBatch;
     

    public static StorePPx store() {
        if (store == null) store = new StorePPx(StoreTransmitBatch.P_Store);
        return store;
    }

    public static StoreBatchPPx storeBatches() {
        if (storeBatches == null) storeBatches = new StoreBatchPPx(StoreTransmitBatch.P_StoreBatches);
        return storeBatches;
    }

    public static StoreTransmitInfoPPx storeTransmitInfos() {
        if (storeTransmitInfos == null) storeTransmitInfos = new StoreTransmitInfoPPx(StoreTransmitBatch.P_StoreTransmitInfos);
        return storeTransmitInfos;
    }

    public static TransmitBatchPPx transmitBatch() {
        if (transmitBatch == null) transmitBatch = new TransmitBatchPPx(StoreTransmitBatch.P_TransmitBatch);
        return transmitBatch;
    }

    public static String storeNumber() {
        String s = StoreTransmitBatch.P_StoreNumber;
        return s;
    }

    public static String transmitBatchDate() {
        String s = StoreTransmitBatch.P_TransmitBatchDate;
        return s;
    }

    public static String greenMessageAdded() {
        String s = StoreTransmitBatch.P_GreenMessageAdded;
        return s;
    }

    public static String batchProcessed() {
        String s = StoreTransmitBatch.P_BatchProcessed;
        return s;
    }

    public static String storeTransmitProcessed() {
        String s = StoreTransmitBatch.P_StoreTransmitProcessed;
        return s;
    }

    public static String storeTransmitPostProcessProcessed() {
        String s = StoreTransmitBatch.P_StoreTransmitPostProcessProcessed;
        return s;
    }

    public static String storeStatus() {
        String s = StoreTransmitBatch.P_StoreStatus;
        return s;
    }

    public static String getTotalSendCount() {
        String s = "getTotalSendCount";
        return s;
    }

    public static String pp() {
        return ""; // this
    }
}
 
