// Generated by OABuilder
package com.corptostore.model.oa.propertypath;
 
import java.io.Serializable;

import com.corptostore.model.oa.*;
import com.corptostore.model.oa.TesterStep;
import com.corptostore.model.oa.propertypath.PPxInterface;
import com.corptostore.model.oa.propertypath.TesterPPx;
import com.corptostore.model.oa.propertypath.TesterStepTypePPx;
 
public class TesterStepPPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
     
    public TesterStepPPx(String name) {
        this(null, name);
    }

    public TesterStepPPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null && name.length() > 0) {
            if (s.length() > 0 && name.charAt(0) != ':') s += ".";
            s += name;
        }
        pp = s;
    }

    public TesterPPx calcTester() {
        TesterPPx ppx = new TesterPPx(this, TesterStep.P_CalcTester);
        return ppx;
    }

    public TesterPPx tester() {
        TesterPPx ppx = new TesterPPx(this, TesterStep.P_Tester);
        return ppx;
    }

    public TesterStepTypePPx testerStepType() {
        TesterStepTypePPx ppx = new TesterStepTypePPx(this, TesterStep.P_TesterStepType);
        return ppx;
    }

    public String id() {
        return pp + "." + TesterStep.P_Id;
    }

    public String created() {
        return pp + "." + TesterStep.P_Created;
    }

    public String started() {
        return pp + "." + TesterStep.P_Started;
    }

    public String ended() {
        return pp + "." + TesterStep.P_Ended;
    }

    @Override
    public String toString() {
        return pp;
    }
    public String pp() {
        return pp;
    }
}
 
