// Generated by OABuilder
package com.messagedesigner.model.search;

import java.util.logging.*;

import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.filter.*;
import com.messagedesigner.delegate.ModelDelegate;
import com.messagedesigner.model.*;
import com.messagedesigner.model.oa.*;
import com.messagedesigner.model.oa.filter.*;
import com.messagedesigner.model.oa.propertypath.*;
import com.messagedesigner.model.oa.search.*;
import com.messagedesigner.resource.Resource;
import com.messagedesigner.model.oa.MessageType;
import com.messagedesigner.model.oa.search.MessageTypeSearch;
import com.messagedesigner.model.search.MessageTypeSearchModel;
import com.viaoa.datasource.*;

public class MessageTypeSearchModel {
    private static Logger LOG = Logger.getLogger(MessageTypeSearchModel.class.getName());
    
    protected Hub<MessageType> hub;  // search results
    protected Hub<MessageType> hubMultiSelect;
    protected Hub<MessageType> hubSearchFrom;  // hub (optional) to search from
    protected Hub<MessageTypeSearch> hubMessageTypeSearch;  // search data, size=1, AO
    
    // finder used to find objects in a path
    protected OAFinder<?, MessageType> finder;
    
    // object used for search data
    protected MessageTypeSearch messageTypeSearch;
    
    public MessageTypeSearchModel() {
    }
    
    public MessageTypeSearchModel(Hub<MessageType> hub) {
        this.hub = hub;
    }
    
    // hub used for search results
    public Hub<MessageType> getHub() {
        if (hub == null) {
            hub = new Hub<MessageType>(MessageType.class);
        }
        return hub;
    }
    
    // hub used to search within
    private HubListener hlSearchFromHub;
    public Hub<MessageType> getSearchFromHub() {
        return hubSearchFrom;
    }
    public void setSearchFromHub(Hub<MessageType> hub) {
        if (this.hlSearchFromHub != null) {
            hubSearchFrom.removeListener(hlSearchFromHub);
            hlSearchFromHub = null;
        }
    
        hubSearchFrom = hub;
        if (hubSearchFrom != null) {
            hlSearchFromHub = new HubListenerAdapter() {
                @Override
                public void onNewList(HubEvent e) {
                    MessageTypeSearchModel.this.getHub().clear();
                }
            };
            hubSearchFrom.addHubListener(hlSearchFromHub);
        }
    }
    public void close() {
        setSearchFromHub(null);
    }
    
    public Hub<MessageType> getMultiSelectHub() {
        if (hubMultiSelect == null) {
            hubMultiSelect = new Hub<>(MessageType.class);
        }
        return hubMultiSelect;
    }
    
    public OAFinder<?, MessageType> getFinder() {
        return finder;
    }
    public void setFinder(OAFinder<?, MessageType> finder) {
        this.finder = finder;
    }
    
    // object used to input query data, to be used by searchHub
    public MessageTypeSearch getMessageTypeSearch() {
        if (messageTypeSearch != null) return messageTypeSearch;
        messageTypeSearch = new MessageTypeSearch();
        return messageTypeSearch;
    }
    
    // hub for search object - used to bind with UI components for entering search data
    public Hub<MessageTypeSearch> getMessageTypeSearchHub() {
        if (hubMessageTypeSearch == null) {
            hubMessageTypeSearch = new Hub<MessageTypeSearch>(MessageTypeSearch.class);
            hubMessageTypeSearch.add(getMessageTypeSearch());
            hubMessageTypeSearch.setPos(0);
        }
        return hubMessageTypeSearch;
    }
    
    
    
    public void beforeInput() {
        // hook that is called before search input starts
    }
    
    // uses MessageTypeSearch to build query, and populate Hub 
    public void performSearch() {
        OASelect<MessageType> sel = getMessageTypeSearch().getSelect();
        sel.setSearchHub(getSearchFromHub());
        sel.setFinder(getFinder());
        getHub().select(sel);
    }
    
    // can to overwritten to know when a selection is made
    public void onSelect(MessageType messageType, Hub<MessageType> hub) {
    }
    // can to overwritten to know when a multi-select is made
    public void onSelect(Hub<MessageType> hub) {
    }
}

