// Generated by OABuilder
package com.messagedesigner.model.search;

import java.util.logging.*;

import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.filter.*;
import com.messagedesigner.delegate.ModelDelegate;
import com.messagedesigner.model.*;
import com.messagedesigner.model.oa.*;
import com.messagedesigner.model.oa.filter.*;
import com.messagedesigner.model.oa.propertypath.*;
import com.messagedesigner.model.oa.search.*;
import com.messagedesigner.resource.Resource;
import com.messagedesigner.model.oa.MessageConfig;
import com.messagedesigner.model.oa.search.MessageConfigSearch;
import com.messagedesigner.model.search.MessageConfigSearchModel;
import com.viaoa.datasource.*;

public class MessageConfigSearchModel {
    private static Logger LOG = Logger.getLogger(MessageConfigSearchModel.class.getName());
    
    protected Hub<MessageConfig> hub;  // search results
    protected Hub<MessageConfig> hubMultiSelect;
    protected Hub<MessageConfig> hubSearchFrom;  // hub (optional) to search from
    protected Hub<MessageConfigSearch> hubMessageConfigSearch;  // search data, size=1, AO
    
    // finder used to find objects in a path
    protected OAFinder<?, MessageConfig> finder;
    
    // object used for search data
    protected MessageConfigSearch messageConfigSearch;
    
    public MessageConfigSearchModel() {
    }
    
    public MessageConfigSearchModel(Hub<MessageConfig> hub) {
        this.hub = hub;
    }
    
    // hub used for search results
    public Hub<MessageConfig> getHub() {
        if (hub == null) {
            hub = new Hub<MessageConfig>(MessageConfig.class);
        }
        return hub;
    }
    
    // hub used to search within
    private HubListener hlSearchFromHub;
    public Hub<MessageConfig> getSearchFromHub() {
        return hubSearchFrom;
    }
    public void setSearchFromHub(Hub<MessageConfig> hub) {
        if (this.hlSearchFromHub != null) {
            hubSearchFrom.removeListener(hlSearchFromHub);
            hlSearchFromHub = null;
        }
    
        hubSearchFrom = hub;
        if (hubSearchFrom != null) {
            hlSearchFromHub = new HubListenerAdapter() {
                @Override
                public void onNewList(HubEvent e) {
                    MessageConfigSearchModel.this.getHub().clear();
                }
            };
            hubSearchFrom.addHubListener(hlSearchFromHub);
        }
    }
    public void close() {
        setSearchFromHub(null);
    }
    
    public Hub<MessageConfig> getMultiSelectHub() {
        if (hubMultiSelect == null) {
            hubMultiSelect = new Hub<>(MessageConfig.class);
        }
        return hubMultiSelect;
    }
    
    public OAFinder<?, MessageConfig> getFinder() {
        return finder;
    }
    public void setFinder(OAFinder<?, MessageConfig> finder) {
        this.finder = finder;
    }
    
    // object used to input query data, to be used by searchHub
    public MessageConfigSearch getMessageConfigSearch() {
        if (messageConfigSearch != null) return messageConfigSearch;
        messageConfigSearch = new MessageConfigSearch();
        return messageConfigSearch;
    }
    
    // hub for search object - used to bind with UI components for entering search data
    public Hub<MessageConfigSearch> getMessageConfigSearchHub() {
        if (hubMessageConfigSearch == null) {
            hubMessageConfigSearch = new Hub<MessageConfigSearch>(MessageConfigSearch.class);
            hubMessageConfigSearch.add(getMessageConfigSearch());
            hubMessageConfigSearch.setPos(0);
        }
        return hubMessageConfigSearch;
    }
    
    
    
    public void beforeInput() {
        // hook that is called before search input starts
    }
    
    // uses MessageConfigSearch to build query, and populate Hub 
    public void performSearch() {
        OASelect<MessageConfig> sel = getMessageConfigSearch().getSelect();
        sel.setSearchHub(getSearchFromHub());
        sel.setFinder(getFinder());
        getHub().select(sel);
    }
    
    // can to overwritten to know when a selection is made
    public void onSelect(MessageConfig messageConfig, Hub<MessageConfig> hub) {
    }
    // can to overwritten to know when a multi-select is made
    public void onSelect(Hub<MessageConfig> hub) {
    }
}

