// Generated by OABuilder
package com.oreillyauto.dev.tool.messagedesigner.model.oa.propertypath;
 
import java.io.Serializable;
import com.oreillyauto.dev.tool.messagedesigner.model.oa.*;
 
public class MessageRecordPPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
     
    public MessageRecordPPx(String name) {
        this(null, name);
    }

    public MessageRecordPPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null && name.length() > 0) {
            if (s.length() > 0 && name.charAt(0) != ':') s += ".";
            s += name;
        }
        pp = s;
    }

    public MessageGroupPPx messageGroup() {
        MessageGroupPPx ppx = new MessageGroupPPx(this, MessageRecord.P_MessageGroup);
        return ppx;
    }

    public MessageTypePPx messageType() {
        MessageTypePPx ppx = new MessageTypePPx(this, MessageRecord.P_MessageType);
        return ppx;
    }

    public MessageTypeRecordPPx messageTypeRecord() {
        MessageTypeRecordPPx ppx = new MessageTypeRecordPPx(this, MessageRecord.P_MessageTypeRecord);
        return ppx;
    }

    public String id() {
        return pp + "." + MessageRecord.P_Id;
    }

    public String created() {
        return pp + "." + MessageRecord.P_Created;
    }

    public String relationshipType() {
        return pp + "." + MessageRecord.P_RelationshipType;
    }

    public String seq() {
        return pp + "." + MessageRecord.P_Seq;
    }

    public String display() {
        return pp + "." + MessageRecord.P_Display;
    }

    public MessageRecordPPx typeManyFilter() {
        MessageRecordPPx ppx = new MessageRecordPPx(this, ":typeMany()");
        return ppx;
    }

    @Override
    public String toString() {
        return pp;
    }
    public String pp() {
        return pp;
    }
}
 
