/*
 * Copyright 1999–2025 ViaOA (info@viaoa.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.viaoa.remote;

import java.util.logging.Logger;

import com.viaoa.object.OAThreadLocalDelegate;
import com.viaoa.remote.info.RequestInfo;
import com.viaoa.runtime.OARuntime;

/**
 * A specialized thread used by OA's remote messaging framework to process
 * incoming remote method calls, broadcasts, and ripple-effect events.
 * <p>
 * Each {@code OARemoteThread} represents the execution context for a single
 * remote request. It tracks internal state so the remote subsystem can
 * determine when:
 * </p>
 * <ul>
 *   <li>the thread has reached its primary “mark” and another thread may begin
 *       processing the next remote message,</li>
 *   <li>synchronous or asynchronous events generated inside the thread should
 *       be broadcast to other clients,</li>
 *   <li>the thread is blocked on an {@code OAThreadLocalDelegate} lock,</li>
 *   <li>queued runnables are allowed to run inside this thread.</li>
 * </ul>
 *
 * <p>
 * Most applications do not interact with {@code OARemoteThread} directly.
 * Runtime checks and coordination are done through
 * {@link OARemoteThreadDelegate}.
 * </p>
 *
 * <p>
 * Before a remote thread begins processing the next message,
 * {@link #reset()} is called to clear internal state and reset the
 * {@code OAThreadLocalDelegate} context.
 * </p>
 */
public class OARemoteThread extends Thread {
	private static Logger LOG = Logger.getLogger(OARemoteThread.class.getName());

	/**
	 * Lock object used for synchronization when coordinating access to shared
	 * state within this remote thread.
	 */
	public final Object Lock = new Object();
	
	/**
	 * Counter used to track the number of warning messages generated by remote
	 * thread operations.
	 */
	private static int warningMsgCnt;

	/**
	 * Indicates whether a stop request has been issued for this thread. Marked
	 * volatile so other threads can observe changes immediately.
	 */
	public volatile boolean stopCalled;
	
	/**
	 * The {@link RequestInfo} associated with the remote request being processed
	 * by this thread.
	 */
	public volatile RequestInfo requestInfo;
	
	/**
	 * Whether this thread has signaled that the next remote thread may begin
	 * processing a new message.
	 */
	public volatile boolean startedNextThread;
	
	/**
	 * Flag indicating whether this thread is currently waiting on a lock set by
	 * {@code OAThreadLocalDelegate}. Spelling preserved from source.
	 */
	public volatile boolean watingOnLock;
	
	/**
	 * Timestamp (in milliseconds) recorded when this thread signals that the next
	 * thread may begin processing.
	 */
	public volatile long msStartNextThread;
	
	/**
	 * Timestamp (in milliseconds) indicating the last time this thread was used
	 * for remote message processing.
	 */
	public volatile long msLastUsed;
	
	/**
	 * Counter used to determine whether OASync changes should be broadcast to
	 * other computers. A value greater than zero enables sending messages.
	 */
	private volatile int sendMessageCount;  // if ==  0 (default) then sendMessages is false, else true

	/**
	 * Creates a new {@code OARemoteThread} with no initial runnable. No additional
	 * initialization is performed.
	 */
	public OARemoteThread() {
	}

	/**
	 * Creates a new {@code OARemoteThread} configured with the specified runnable.
	 *
	 * @param r the runnable to execute when this thread is started
	 */
	public OARemoteThread(Runnable r) {
		super(r);
	}

	/**
	 * Flag indicating whether runnables added to this thread may be executed by
	 * another thread or thread pool.
	 */
	private boolean bAllowRunnable;

	/**
	 * Sets whether runnables added to this thread may be executed externally
	 * rather than directly within this thread.
	 *
	 * @param b true to allow external execution, false otherwise
	 */
	public void setAllowRunnable(boolean b) {
		bAllowRunnable = b;
	}

	/**
	 * Returns whether runnables added to this thread may be executed by another
	 * thread or thread pool.
	 *
	 * @return true if external execution is allowed, otherwise false
	 */
	public boolean getAllowRunnable() {
		return bAllowRunnable;
	}

	/**
	 * Adds a runnable to this thread. By default, the runnable is executed
	 * immediately by invoking {@code r.run()}. If {@code r} is null, the call is
	 * ignored.
	 *
	 * @param r the runnable to execute
	 */
	public void addRunnable(Runnable r) {
		if (r == null) {
			return;
		}
		r.run();
	}

	/**
	 * Marks that this thread has reached its primary execution point and records
	 * the timestamp, allowing another thread to begin processing the next message.
	 */
	public void startNextThread() {
		startedNextThread = true;
		msStartNextThread = System.currentTimeMillis();
	}

	/**
	 * Indicates whether this thread has signaled that the next thread may begin
	 * processing a remote message.
	 *
	 * @return true if the next thread has been started, otherwise false
	 */
	public boolean startedNextThread() {
		return startedNextThread;
	}

	/*
	 * Any OAsync changes (OAObject/Hub) that are made within an OARemoteThread will not be broadcast to other computers, since they will
	 * also be processing the same originating message. This can be set to true, so that any OASync changes will be sent out. This is useful
	 * when an event listener will only run on the server, and any sync changes will then be sent to others. False by default.
	 */
	/**
	 * Adjusts whether OASync messages should be broadcast to other systems. Each
	 * true value increments the internal counter; false decrements it.
	 *
	 * @param b true to increase the send counter, false to decrease it
	 */
	public void setSendMessages(boolean b) {
		if (b) {
			sendMessageCount++;
		} else {
			sendMessageCount--;
		}
	}

	/**
	 * Determines whether OASync changes made within this thread should be
	 * broadcast to other computers.
	 *
	 * @return true if send message count is greater than zero, otherwise false
	 */
	public boolean getSendMessages() {
		return sendMessageCount > 0;
	}

	/**
	 * Sets whether this thread is currently waiting on a lock established by
	 * {@code OAThreadLocalDelegate}.
	 *
	 * @param b true if waiting on a lock, otherwise false
	 */
	public void setWaitingOnLock(boolean b) {
		watingOnLock = b;
	}

	/**
	 * Returns whether this thread is currently waiting on a lock created by
	 * {@code OAThreadLocalDelegate}.
	 *
	 * @return true if the thread is waiting on a lock, otherwise false
	 */
	public boolean isWaitingOnLock() {
		return watingOnLock;
	}

	/**
	 * Sets the internal flag that indicates whether this thread has signaled that
	 * the next remote thread may begin processing.
	 *
	 * @param b true to mark as having started the next thread, false otherwise
	 */
	public void setStartedNextThread(boolean b) {
		startedNextThread = b;
	}

	/**
	 * Resets this thread's internal state before processing the next OASync
	 * message. This includes clearing message flags, timestamps, and resetting the
	 * {@code OAThreadLocalDelegate} context and admin mode.
	 */
	public void reset() {
		// sendMessages = false;
		sendMessageCount = 0;
		startedNextThread = false;
		watingOnLock = false;
		msStartNextThread = 0l;

		// reset thread local
		OARuntime.get().threadLocals().setContext(null);
		OARuntime.get().threadLocals().setAdmin(false);
	}
}
