// Generated by OABuilder
package com.cdi.model.oa.filter;

import java.util.logging.*;
import com.cdi.model.oa.*;
import com.cdi.model.oa.propertypath.*;
import com.viaoa.annotation.*;
import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import java.util.*;
import com.cdi.model.search.*;
import com.cdi.model.oa.search.*;

@OAClass(useDataSource=false, localOnly=true)
@OAClassFilter(name = "Active", displayName = "Active", hasInputParams = false)
public class ItemAddOnActiveFilter extends OAObject implements CustomHubFilter<ItemAddOn> {
    private static final long serialVersionUID = 1L;
    private static Logger LOG = Logger.getLogger(ItemAddOnActiveFilter.class.getName());

    public static final String PPCode = ":Active()";
    private Hub<ItemAddOn> hubMaster;
    private Hub<ItemAddOn> hub;
    private HubFilter<ItemAddOn> hubFilter;
    private OAObjectCacheFilter<ItemAddOn> cacheFilter;
    private boolean bUseObjectCache;

    public ItemAddOnActiveFilter() {
        this(null, null, false);
    }
    public ItemAddOnActiveFilter(Hub<ItemAddOn> hub) {
        this(null, hub, true);
    }
    public ItemAddOnActiveFilter(Hub<ItemAddOn> hubMaster, Hub<ItemAddOn> hub) {
        this(hubMaster, hub, false);
    }
    public ItemAddOnActiveFilter(Hub<ItemAddOn> hubMaster, Hub<ItemAddOn> hubFiltered, boolean bUseObjectCache) {
        this.hubMaster = hubMaster;
        this.hub = hubFiltered;
        this.bUseObjectCache = bUseObjectCache;
        if (hubMaster != null) getHubFilter();
        if (bUseObjectCache) getObjectCacheFilter();
    }


    public void reset() {
    }

    public boolean isDataEntered() {
        return false;
    }
    public void refresh() {
        if (hubFilter != null) getHubFilter().refresh();
        if (cacheFilter != null) getObjectCacheFilter().refresh();
    }

    @Override
    public HubFilter<ItemAddOn> getHubFilter() {
        if (hubFilter != null) return hubFilter;
        if (hubMaster == null) return null;
        hubFilter = new HubFilter<ItemAddOn>(hubMaster, hub) {
            @Override
            public boolean isUsed(ItemAddOn itemAddOn) {
                return ItemAddOnActiveFilter.this.isUsed(itemAddOn);
            }
        };
        hubFilter.addDependentProperty(ItemAddOnPP.discontinuedDate(), false);
        hubFilter.refresh();
        return hubFilter;
    }

    public OAObjectCacheFilter<ItemAddOn> getObjectCacheFilter() {
        if (cacheFilter != null) return cacheFilter;
        if (!bUseObjectCache) return null;
        cacheFilter = new OAObjectCacheFilter<ItemAddOn>(hub) {
            @Override
            public boolean isUsed(ItemAddOn itemAddOn) {
                return ItemAddOnActiveFilter.this.isUsed(itemAddOn);
            }
            @Override
            protected void reselect() {
                ItemAddOnActiveFilter.this.reselect();
            }
        };
        cacheFilter.addDependentProperty(ItemAddOnPP.discontinuedDate(), false);
        cacheFilter.refresh();
        return cacheFilter;
    }

    public void reselect() {
        // can be overwritten to query datasource
    }

    // ==================
    // this method has custom code that will need to be put into the OABuilder filter

    @Override
    public boolean isUsed(ItemAddOn itemAddOn) {
        OADate discontinuedDate = itemAddOn.getDiscontinuedDate();
        return (discontinuedDate == null);
    }
}
