/*
 * Copyright 1999–2025 ViaOA (info@viaoa.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.viaoa.annotation;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/*qqqqqqqqqqq
CODEX

5. OAClass.isPreSelect() — annotation value is not loaded into OAObjectInfo
     Severity: Low
     Execution path: class declares @OAClass(isPreSelect=true). OAObjectInfo has setPreSelect/getPreSelect, and
     runtime references getPreSelect() in object event diagnostics, but OAObjectAnnotationService never calls
     oi.setPreSelect(oaclass.isPreSelect()).
     Why it matters: annotated preselect metadata is silently lost. Current observed impact is limited, but any
     runtime path relying on OAObjectInfo.getPreSelect() will see false for annotated classes.
     Minimal hardening: copy oaclass.isPreSelect() into OAObjectInfo during class annotation processing, or remove/
     document as unsupported.
     Suggested CODEX comment location: OAObjectAnnotationService._update, class-level @OAClass load block.


*/

/**
 * Class-level metadata describing an {@link OAObject} type and its
 * runtime/persistence/UI behavior within the OA Framework.
 *
 * <p>This annotation is generated by OABuilder and read by
 * {@link OAObjectInfo} to establish the object’s name, caching rules,
 * initialization behavior, soft-delete fields, sorting defaults, and 
 * special handling such as singletons or POJO-less mode.</p>
 *
 * <p><b>Key Responsibilities</b>
 * <ul>
 *   <li>Define display names, plural names, and JSON naming rules.</li>
 *   <li>Control persistence: {@code useDataSource}, {@code localOnly},
 *       {@code addToCache}, {@code softDeleteProperty}.</li>
 *   <li>UI and UX integration: {@code displayProperty}, 
 *       {@code sortProperty}, {@code viewProperties}.</li>
 *   <li>Model-driven features: version properties, time-series properties,
 *       freeze property, processed flags.</li>
 *   <li>Graph-navigation hints: {@code rootTreePropertyPaths},
 *       {@code filterClasses}.</li>
 * </ul>
 *
 * <p>The annotation is central to OA’s “metadata-driven object graph”
 * design, enabling the framework to behave generically while preserving
 * domain semantics defined in the OABuilder model.</p>
 */
@Documented
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
public @interface OAClass {

	String shortName() default "";

	String pluralName() default "";

	String lowerName() default "";

	String displayName() default "";

	String description() default "";

	boolean isLookup() default false;

	boolean isPreSelect() default false;

	/** @return flag used to determine if object can be stored to datasource. */
	boolean useDataSource() default true;

	/** @return flag to know if objects should be added to cache */
	boolean addToCache() default true;

	/** @return if true, then changes are not sent to sever. */
	boolean localOnly() default false;

	/** @return if false, then objects are not initialized on creation */
	boolean initialize() default true;

	String displayProperty() default "";

	String sortProperty() default "";

	//String[] searchProperties() default {};
	String[] viewProperties() default {};

	long estimatedTotal() default 0;

	Class[] filterClasses() default {};

	// property path from a root class to this class.
	String[] rootTreePropertyPaths() default {};

	/** flag to know if this is processed and will require User.editProcessed=true for it to be changed. */
	boolean isProcessed() default false;

	String softDeleteProperty() default "";

	String softDeleteReasonProperty() default "";

	String versionProperty() default "";

	String versionLinkProperty() default "";

	String timeSeriesProperty() default "";

    String freezeProperty() default "";
	
	boolean singleton() default false;

	boolean pojoSingleton() default false;

	boolean noPojo() default false;
	
	boolean jsonUsesCapital() default false;  // JSON names use a capital letter (titled case)
	
	
	/**
	 * Used to flag the single class in a model that represents runtime User.
	 */
	boolean isModelUserClass() default false;
	
}

/* used by OAObjectInfo
    protected boolean bUseDataSource = true;
    protected boolean bLocalOnly = false;  // dont send to OAServer
    protected boolean bAddToCache = true;  // add object to Cache
    protected boolean bInitializeNewObjects = true;  // initialize object properties (used by OAObject)
    protected String displayName;



*/