/*
 * Copyright 1999–2025 ViaOA (info@viaoa.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.viaoa.annotation;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;


/**
 * Class-level metadata describing an {@link OAObject} type and its
 * runtime/persistence/UI behavior within the OA Framework.
 *
 * <p>This annotation is generated by OABuilder and read by
 * {@link OAObjectInfo} to establish the object’s name, caching rules,
 * initialization behavior, soft-delete fields, sorting defaults, and 
 * special handling such as singletons or POJO-less mode.</p>
 *
 * <p><b>Key Responsibilities</b>
 * <ul>
 *   <li>Define display names, plural names, and JSON naming rules.</li>
 *   <li>Control persistence: {@code useDataSource}, {@code localOnly},
 *       {@code addToCache}, {@code softDeleteProperty}.</li>
 *   <li>UI and UX integration: {@code displayProperty}, 
 *       {@code sortProperty}, {@code viewProperties}.</li>
 *   <li>Model-driven features: version properties, time-series properties,
 *       freeze property, processed flags.</li>
 *   <li>OA model navigation hints: {@code rootTreePaths},
 *       {@code filterClasses}.</li>
 * </ul>
 *
 * <p>The annotation is central to OA’s “metadata-driven OA model”
 * design, enabling the framework to behave generically while preserving
 * domain semantics defined in the OABuilder model.</p>
 */
@Documented
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
public @interface OAClass {

	/**
	 * Short internal name for the model class.
	 * @return short class name, or empty string
	 */
	String shortName() default "";

	/**
	 * Plural display name for collections of this class.
	 * @return plural display name, or empty string
	 */
	String pluralName() default "";

	/**
	 * Lowercase metadata name used for normalized lookup.
	 * @return lowercase class name, or empty string
	 */
	String lowerName() default "";

	/**
	 * Human-readable display name for this class.
	 * @return display name, or empty string
	 */
	String displayName() default "";

	/**
	 * Description used by generated UI, documentation, or tooling.
	 * @return class description, or empty string
	 */
	String description() default "";

	/**
	 * Marks this class as lookup/reference data.
	 * @return {@code true} if this class is lookup data
	 */
	boolean isLookup() default false;

	/**
	 * Marks this class as a preselect candidate for runtime loading behavior.
	 * @return {@code true} if preselect metadata is enabled
	 */
	boolean isPreSelect() default false;

	/** @return flag used to determine if object can be stored to datasource. */
	boolean useDataSource() default true;

	/** @return flag to know if objects should be added to cache */
	boolean addToCache() default true;

	/** @return if true, then changes are not sent to sever. */
	boolean localOnly() default false;

	/** @return if false, then objects are not initialized on creation */
	boolean initialize() default true;

	/**
	 * Property used as the default display value for object instances.
	 * @return display property name, or empty string
	 */
	String displayProperty() default "";

	/**
	 * Property path used for default sorting.
	 * @return default sort property path, or empty string
	 */
	String sortProperty() default "";

	//String[] searchProperties() default {};
	/**
	 * Property names or paths commonly shown for this class.
	 * @return view property names or paths
	 */
	String[] viewProperties() default {};

	/**
	 * Estimated object count used by generated UI, tooling, or runtime hints.
	 * @return estimated total count
	 */
	long estimatedTotal() default 0;

	/**
	 * Filter classes associated with this model class.
	 * @return filter classes
	 */
	Class[] filterClasses() default {};

	// property path from a root class to this class.
	/**
	 * Property paths from root classes to this class.
	 * @return root tree property paths
	 */
	String[] rootTreePaths() default {};

	/** flag to know if this is processed and will require User.editProcessed=true for it to be changed. */
	boolean isProcessed() default false;

	/**
	 * Property used to mark soft-deleted objects.
	 * @return soft-delete property name, or empty string
	 */
	String softDeleteProperty() default "";

	/**
	 * Property used to store a soft-delete reason.
	 * @return soft-delete reason property name, or empty string
	 */
	String softDeleteReasonProperty() default "";

	/**
	 * Property used for version or optimistic concurrency metadata.
	 * @return version property name, or empty string
	 */
	String versionProperty() default "";

	/**
	 * Link property associated with version metadata.
	 * @return version link property name, or empty string
	 */
	String versionLinkProperty() default "";

	/**
	 * Property used for time-series grouping or ordering.
	 * @return time-series property name, or empty string
	 */
	String timeSeriesProperty() default "";

	/**
	 * Property used to mark objects as frozen/read-only.
	 * @return freeze property name, or empty string
	 */
    String freezeProperty() default "";
	
	/**
	 * Marks this class as having a singleton runtime instance.
	 * @return {@code true} if this class is singleton-scoped
	 */
	boolean singleton() default false;

	/**
	 * Marks this class as a singleton for POJO generation/integration.
	 * @return {@code true} if POJO singleton metadata is enabled
	 */
	boolean pojoSingleton() default false;

	/**
	 * Suppresses POJO generation or POJO mapping for this class.
	 * @return {@code true} if POJO support is disabled
	 */
	boolean noPojo() default false;
	
	/**
	 * Uses title-case property names in JSON output.
	 * @return {@code true} if JSON names use an initial capital letter
	 */
	boolean jsonUsesCapital() default false;  // JSON names use a capital letter (titled case)
	
	
	/**
	 * Used to flag the single class in a model that represents runtime User.
	 */
	boolean isModelUserClass() default false;
	
}

/* used by OAObjectInfo
    protected boolean bUseDataSource = true;
    protected boolean bLocalOnly = false;  // dont send to OAServer
    protected boolean bAddToCache = true;  // add object to Cache
    protected boolean bInitializeNewObjects = true;  // initialize object properties (used by OAObject)
    protected String displayName;



*/