/*
 * Copyright 1999–2025 ViaOA (info@viaoa.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Provides the full set of annotations used to describe the metadata for
 * {@link com.viaoa.object.OAObject} classes generated by OABuilder and
 * interpreted by the OA runtime through {@link com.viaoa.object.OAObjectInfo}.
 *
 * <p>
 * OA annotations define the structural, relational, and behavioral
 * characteristics of each model object in the OA Object Graph.
 * They describe properties, links, database mappings, calculated fields,
 * triggers, filters, and UI-level behaviors.  
 * This metadata drives:
 * </p>
 *
 * <ul>
 *   <li>object identity and primary keys</li>
 *   <li>simple properties and validation rules</li>
 *   <li>one-to-one, one-to-many, and many-to-many relationships</li>
 *   <li>database table and column mappings</li>
 *   <li>link-table definitions for M2M relationships</li>
 *   <li>calculated properties and dependent property paths</li>
 *   <li>trigger methods listening to property-path changes</li>
 *   <li>import-match logic for object creation during JSON/POJO import</li>
 *   <li>UI visibility/enabled callback methods</li>
 *   <li>class-level configuration (caching, initialization, local-only)</li>
 * </ul>
 *
 * <p>
 * The annotations form the "schema" of an OA application.  
 * OABuilder generates them from the model design, and at runtime OA converts
 * this metadata into an {@link com.viaoa.object.OAObjectInfo} instance that
 * drives all major framework features, including:
 * </p>
 *
 * <ul>
 *   <li>automatic Hub creation and wiring</li>
 *   <li>object graph traversal and observability</li>
 *   <li>validation and defaulting</li>
 *   <li>persistence and SQL mapping</li>
 *   <li>JSON/XML serialization</li>
 *   <li>distributed sync and change propagation</li>
 *   <li>UI generation in OA-Web and OA-JFC</li>
 * </ul>
 *
 * <p>
 * In summary, <b>this package defines the declarative metadata language of the
 * OA platform</b>.  
 * The annotations describe the model, and the OA runtime
 * uses that metadata to automate object behavior, persistence, messaging,
 * and UI representation throughout the application.
 * </p>
 *
 * @author
 *   ViaOA / OABuilder
 */
package com.viaoa.annotation;

