/*
 * Copyright 1999–2025 ViaOA (info@viaoa.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.viaoa.metadata;

import java.lang.reflect.Method;

import com.viaoa.annotation.OAMethod;
import com.viaoa.object.OAObject;

/**
 * Metadata descriptor for a method on an OAObject type. OAMethodInfo identifies
 * a Java method and its signature so the OA runtime can invoke it dynamically
 * for triggers, lifecycle callbacks, and calculated property evaluation.
 *
 * <p>Method metadata is generated by OABuilder from the application model or
 * discovered through reflection during metadata initialization. It enables the
 * OA runtime to integrate behavior directly into the Object Graph without
 * requiring hard-coded registration or lookup logic.</p>
 *
 * <p>OAMethodInfo instances are immutable after construction and are retrieved
 * through OAObjectInfo to support dynamic behavior execution based entirely on
 * model metadata.</p>
 *
 * @see OAObjectInfo
 * @see OAPropertyInfo
 * @see OACalcInfo
 * @see OAObject
 */
public class OAMethodInfo implements java.io.Serializable {
    static final long serialVersionUID = 1L;    

    /**
     * The name of the method represented by this metadata entry.
     */
	private String name;

	/**
	 * Name of the property that determines whether this method is enabled.
	 */
    private String enabledProperty;

    /**
     * Boolean value that must be matched for the method to be enabled.
     */
    private boolean enabledValue;
    
    /**
     * Name of the property that determines whether this method is visible.
     */
    private String visibleProperty;
    
    /**
     * Boolean value that must be matched for the method to be visible.
     */
    private boolean visibleValue;
	
    /**
     * Name of the property that determines whether this method is enabled
     * based on the current context.
     */
    private String contextEnabledProperty;
    
    /**
     * Context-based enabled value that must match for the method to be enabled.
     */
    private boolean contextEnabledValue;
    
    /**
     * Name of the property that determines whether this method is visible
     * based on the current context.
     */
    private String contextVisibleProperty;
    
    /**
     * Context-based visible value that must match for the method to be visible.
     */
    private boolean contextVisibleValue;
    
    /**
     * Java reflection Method invoked when this metadata entry's method is
     * executed dynamically by the OA runtime.
     */
    private transient Method objectCallbackMethod;
    
    /**
     * Annotation metadata describing the method's behavior and configuration.
     */
    private OAMethod oaMethod;
    
    /**
     * Property names whose changes affect the method's visibility state.
     */
    private String[] viewDependentProperties;
    
    /**
     * Property names whose changes affect the method's context-dependent behavior.
     */
    private String[] contextDependentProperties;
    
    /**
     * Creates a new, empty method-metadata descriptor.
     */
	public OAMethodInfo() {
	}

	/**
	 * Returns the name of the method represented by this metadata.
	 *
	 * @return the method name, or {@code null} if not set
	 */
    public String getName() {
		return name;
	}

    /**
     * Sets the name of the method represented by this metadata.
     *
     * @param name the method name
     */
    public void setName(String name) {
		this.name = name;
	}
    
    /**
     * Sets the list of property names that this method's visibility depends on.
     *
     * @param ss an array of dependent property names
     */
    public void setViewDependentProperties(String[] ss) {
        this.viewDependentProperties = ss;
    }

    /**
     * Returns the list of property names that this method's visibility depends on.
     *
     * @return an array of dependent property names, or {@code null} if none are set
     */
    public String[] getViewDependentProperties() {
        return this.viewDependentProperties;
    }	

    /**
     * Sets the list of property names that this method's context-dependent
     * behavior relies on.
     *
     * @param ss an array of context-dependent property names
     */
    public void setContextDependentProperties(String[] ss) {
        this.contextDependentProperties = ss;
    }
    
    /**
     * Returns the list of property names that this method's context-dependent
     * behavior relies on.
     *
     * @return an array of context-dependent property names, or {@code null} if none are set
     */
    public String[] getContextDependentProperties() {
        return this.contextDependentProperties;
    }   
    
    /**
     * Returns the property name used to determine whether this method is enabled.
     *
     * @return the enabled-property name, or {@code null} if none is set
     */
    public String getEnabledProperty() {
        return enabledProperty;
    }

    /**
     * Sets the property name used to determine whether this method is enabled.
     *
     * @param s the enabled-property name
     */
    public void setEnabledProperty(String s) {
        enabledProperty = s;
    }
    
    /**
     * Returns the value that determines whether this method is enabled.
     *
     * @return {@code true} if the method is enabled when the property matches,
     *         otherwise {@code false}
     */
    public boolean getEnabledValue() {
        return enabledValue;
    }
    
    /**
     * Sets the value that determines whether this method is enabled.
     *
     * @param b {@code true} to enable the method when the property matches,
     *          otherwise {@code false}
     */
    public void setEnabledValue(boolean b) {
        enabledValue = b;
    }

    /**
     * Returns the property name used to determine whether this method is visible.
     *
     * @return the visible-property name, or {@code null} if none is set
     */
    public String getVisibleProperty() {
        return visibleProperty;
    }

    /**
     * Sets the property name used to determine whether this method is visible.
     *
     * @param s the visible-property name
     */
    public void setVisibleProperty(String s) {
        visibleProperty = s;
    }
    
    /**
     * Returns the value that determines whether this method is visible.
     *
     * @return {@code true} if the method is visible when the property matches,
     *         otherwise {@code false}
     */
    public boolean getVisibleValue() {
        return visibleValue;
    }
    
    /**
     * Sets the value that determines whether this method is visible.
     *
     * @param b {@code true} to make the method visible when the property matches,
     *          otherwise {@code false}
     */
    public void setVisibleValue(boolean b) {
        visibleValue = b;
    }

    /**
     * Returns the property name used to determine whether this method is enabled
     * based on the current context.
     *
     * @return the context-enabled property name, or {@code null} if none is set
     */
    public String getContextEnabledProperty() {
        return contextEnabledProperty;
    }
    
    /**
     * Sets the property name used to determine whether this method is enabled
     * based on the current context.
     *
     * @param s the context-enabled property name
     */
    public void setContextEnabledProperty(String s) {
        contextEnabledProperty = s;
    }

    /**
     * Returns the value that determines whether this method is enabled
     * based on the current context.
     *
     * @return {@code true} if the method is enabled when the context property matches,
     *         otherwise {@code false}
     */
    public boolean getContextEnabledValue() {
        return contextEnabledValue;
    }
    
    /**
     * Sets the value that determines whether this method is enabled
     * based on the current context.
     *
     * @param b {@code true} to enable the method when the context property matches,
     *          otherwise {@code false}
     */
    public void setContextEnabledValue(boolean b) {
        contextEnabledValue = b;
    }
    
    public String getContextVisibleProperty() {
        return contextVisibleProperty;
    }
    
    /**
     * Sets the property name used to determine whether this method is visible
     * based on the current context.
     *
     * @param s the context-visible property name
     */
    public void setContextVisibleProperty(String s) {
        contextVisibleProperty = s;
    }
    
    /**
     * Returns the value that determines whether this method is visible
     * based on the current context.
     *
     * @return {@code true} if the method is visible when the context property matches,
     *         otherwise {@code false}
     */
    public boolean getContextVisibleValue() {
        return contextVisibleValue;
    }
    
    /**
     * Sets the value that determines whether this method is visible
     * based on the current context.
     *
     * @param b {@code true} to make the method visible when the context property matches,
     *          otherwise {@code false}
     */
    public void setContextVisibleValue(boolean b) {
        contextVisibleValue = b;
    }
    
    /**
     * Sets the value that determines whether this method is visible
     * based on the current context.
     *
     * @param b {@code true} to make the method visible when the context property matches,
     *          otherwise {@code false}
     */
    public void setObjectCallbackMethod(Method m) {
        this.objectCallbackMethod = m;
    }

    /**
     * Returns the callback method associated with this metadata entry.
     *
     * @return the callback {@link Method}, or {@code null} if none is set
     */
    public Method getObjectCallbackMethod() {
        return objectCallbackMethod;
    }
    
    /**
     * Sets the {@link OAMethod} annotation metadata for this method.
     *
     * @param m the {@code OAMethod} annotation instance
     */
    public void setOAMethod(OAMethod m) {
        this.oaMethod = m;
    }
    
    /**
     * Returns the {@link OAMethod} annotation metadata for this method.
     *
     * @return the {@code OAMethod} annotation instance, or {@code null} if none is set
     */
    public OAMethod getOAMethod() {
        return oaMethod;
    }
}
