// Generated by OABuilder
package com.messagedesigner.model.oa.propertypath;
 
import java.io.Serializable;

import com.messagedesigner.model.oa.*;
import com.messagedesigner.model.oa.MessageConfig;
import com.messagedesigner.model.oa.propertypath.PPxInterface;
 
public class MessageConfigPPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
     
    public MessageConfigPPx(String name) {
        this(null, name);
    }

    public MessageConfigPPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null && name.length() > 0) {
            if (s.length() > 0 && name.charAt(0) != ':') s += ".";
            s += name;
        }
        pp = s;
    }

    public String id() {
        return pp + "." + MessageConfig.P_Id;
    }

    public String created() {
        return pp + "." + MessageConfig.P_Created;
    }

    public String console() {
        return pp + "." + MessageConfig.P_Console;
    }

    public String rpgMessageDefinitionFile() {
        return pp + "." + MessageConfig.P_RpgMessageDefinitionFile;
    }

    public String clearMessages() {
        return pp + ".clearMessages";
    }

    public String loadJPOSND() {
        return pp + ".loadJPOSND";
    }

    public String loadJcomm() {
        return pp + ".loadJcomm";
    }

    public String loadRpgMessageFile() {
        return pp + ".loadRpgMessageFile";
    }

    @Override
    public String toString() {
        return pp;
    }
    public String pp() {
        return pp;
    }
}
 
