// Generated by OABuilder
package com.corptostore.model.search;

import java.util.logging.*;

import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.filter.*;
import com.corptostore.delegate.ModelDelegate;
import com.corptostore.model.*;
import com.corptostore.model.oa.*;
import com.corptostore.model.oa.filter.*;
import com.corptostore.model.oa.propertypath.*;
import com.corptostore.model.oa.search.*;
import com.corptostore.resource.Resource;
import com.corptostore.model.oa.TesterStepType;
import com.corptostore.model.oa.search.TesterStepTypeSearch;
import com.corptostore.model.search.TesterStepTypeSearchModel;
import com.viaoa.datasource.*;

public class TesterStepTypeSearchModel {
    private static Logger LOG = Logger.getLogger(TesterStepTypeSearchModel.class.getName());
    
    protected Hub<TesterStepType> hub;  // search results
    protected Hub<TesterStepType> hubMultiSelect;
    protected Hub<TesterStepType> hubSearchFrom;  // hub (optional) to search from
    protected Hub<TesterStepTypeSearch> hubTesterStepTypeSearch;  // search data, size=1, AO
    
    // finder used to find objects in a path
    protected OAFinder<?, TesterStepType> finder;
    
    // object used for search data
    protected TesterStepTypeSearch testerStepTypeSearch;
    
    public TesterStepTypeSearchModel() {
    }
    
    public TesterStepTypeSearchModel(Hub<TesterStepType> hub) {
        this.hub = hub;
    }
    
    // hub used for search results
    public Hub<TesterStepType> getHub() {
        if (hub == null) {
            hub = new Hub<TesterStepType>(TesterStepType.class);
        }
        return hub;
    }
    
    // hub used to search within
    private HubListener hlSearchFromHub;
    public Hub<TesterStepType> getSearchFromHub() {
        return hubSearchFrom;
    }
    public void setSearchFromHub(Hub<TesterStepType> hub) {
        if (this.hlSearchFromHub != null) {
            hubSearchFrom.removeListener(hlSearchFromHub);
            hlSearchFromHub = null;
        }
    
        hubSearchFrom = hub;
        if (hubSearchFrom != null) {
            hlSearchFromHub = new HubListenerAdapter() {
                @Override
                public void onNewList(HubEvent e) {
                    TesterStepTypeSearchModel.this.getHub().clear();
                }
            };
            hubSearchFrom.addHubListener(hlSearchFromHub);
        }
    }
    public void close() {
        setSearchFromHub(null);
    }
    
    public Hub<TesterStepType> getMultiSelectHub() {
        if (hubMultiSelect == null) {
            hubMultiSelect = new Hub<>(TesterStepType.class);
        }
        return hubMultiSelect;
    }
    
    public OAFinder<?, TesterStepType> getFinder() {
        return finder;
    }
    public void setFinder(OAFinder<?, TesterStepType> finder) {
        this.finder = finder;
    }
    
    // object used to input query data, to be used by searchHub
    public TesterStepTypeSearch getTesterStepTypeSearch() {
        if (testerStepTypeSearch != null) return testerStepTypeSearch;
        testerStepTypeSearch = new TesterStepTypeSearch();
        return testerStepTypeSearch;
    }
    
    // hub for search object - used to bind with UI components for entering search data
    public Hub<TesterStepTypeSearch> getTesterStepTypeSearchHub() {
        if (hubTesterStepTypeSearch == null) {
            hubTesterStepTypeSearch = new Hub<TesterStepTypeSearch>(TesterStepTypeSearch.class);
            hubTesterStepTypeSearch.add(getTesterStepTypeSearch());
            hubTesterStepTypeSearch.setPos(0);
        }
        return hubTesterStepTypeSearch;
    }
    
    
    
    public void beforeInput() {
        // hook that is called before search input starts
    }
    
    // uses TesterStepTypeSearch to build query, and populate Hub 
    public void performSearch() {
        OASelect<TesterStepType> sel = getTesterStepTypeSearch().getSelect();
        sel.setSearchHub(getSearchFromHub());
        sel.setFinder(getFinder());
        getHub().select(sel);
    }
    
    // can to overwritten to know when a selection is made
    public void onSelect(TesterStepType testerStepType, Hub<TesterStepType> hub) {
    }
    // can to overwritten to know when a multi-select is made
    public void onSelect(Hub<TesterStepType> hub) {
    }
}

