// Generated by OABuilder
package com.cdi.model.oa;
 
import java.util.*;
import java.util.logging.*;
import java.sql.*;
import com.viaoa.object.*;
import com.viaoa.schedule.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.annotation.*;
import com.viaoa.datetime.OADateTime;
import com.cdi.delegate.oa.*;
import com.cdi.model.oa.filter.*;
import com.cdi.model.oa.propertypath.*;
 
@OAClass(
    lowerName = "chatSession",
    pluralName = "ChatSessions",
    shortName = "chs",
    displayName = "Chat Session",
    useDataSource = false,
    displayProperty = "name",
    noPojo = true
)
public class ChatSession extends OAObject {
    private static final long serialVersionUID = 1L;
    private static Logger LOG = Logger.getLogger(ChatSession.class.getName());

    public static final String P_Id = "id";
    public static final String P_Created = "created";
    public static final String P_Name = "name";
    public static final String P_Inactive = "inactive";
    public static final String P_AllFlag = "allFlag";
     
    public static final String P_CalcLastChatMessage = "calcLastChatMessage";
    public static final String P_ChatMessages = "chatMessages";
    public static final String P_Users = "users";
    public static final String P_UsersId = "usersId"; // fkey
     
    protected volatile int id;
    protected volatile OADateTime created;
    protected volatile String name;
    protected volatile OADateTime inactive;
    protected volatile boolean allFlag;
     
    // Links to other objects.
    protected transient Hub<ChatMessage> hubChatMessages;
    protected transient Hub<User> hubUsers;
     
    public ChatSession() {
        if (!isLoading()) setObjectDefaults();
    }
    @Override
    public void setObjectDefaults() {
        setCreated(new OADateTime());
    }
     
    public ChatSession(int id) {
        this();
        setId(id);
    }

    @OAProperty(lowerName = "id", isUnique = true, trackPrimitiveNull = false, displayLength = 6)
    @OAId
    @OAColumn(name = "Id", sqlType = java.sql.Types.INTEGER)
    public int getId() {
        return id;
    }
    public void setId(int newValue) {
        int old = id;
        fireBeforePropertyChange(P_Id, old, newValue);
        this.id = newValue;
        firePropertyChange(P_Id, old, this.id);
    }

    @OAProperty(lowerName = "created", defaultValue = "new OADateTime()", displayLength = 15, isProcessed = true, ignoreTimeZone = true)
    @OAColumn(name = "Created", sqlType = java.sql.Types.TIMESTAMP)
    public OADateTime getCreated() {
        return created;
    }
    public void setCreated(OADateTime newValue) {
        OADateTime old = created;
        fireBeforePropertyChange(P_Created, old, newValue);
        this.created = newValue;
        firePropertyChange(P_Created, old, this.created);
    }

    @OAProperty(lowerName = "name", maxLength = 50, displayLength = 20)
    @OAColumn(name = "Name", maxLength = 50)
    public String getName() {
        return name;
    }
    public void setName(String newValue) {
        String old = name;
        fireBeforePropertyChange(P_Name, old, newValue);
        this.name = newValue;
        firePropertyChange(P_Name, old, this.name);
    }

    @OAProperty(lowerName = "inactive", displayLength = 15, ignoreTimeZone = true)
    @OAColumn(name = "Inactive", sqlType = java.sql.Types.TIMESTAMP)
    public OADateTime getInactive() {
        return inactive;
    }
    public void setInactive(OADateTime newValue) {
        OADateTime old = inactive;
        fireBeforePropertyChange(P_Inactive, old, newValue);
        this.inactive = newValue;
        firePropertyChange(P_Inactive, old, this.inactive);
    }

    @OAProperty(lowerName = "allFlag", displayName = "All Flag", displayLength = 5, uiColumnLength = 8)
    @OAColumn(name = "AllFlag", sqlType = java.sql.Types.BOOLEAN)
    public boolean getAllFlag() {
        return allFlag;
    }
    public boolean isAllFlag() {
        return getAllFlag();
    }
    public void setAllFlag(boolean newValue) {
        boolean old = allFlag;
        fireBeforePropertyChange(P_AllFlag, old, newValue);
        this.allFlag = newValue;
        firePropertyChange(P_AllFlag, old, this.allFlag);
    }

    @OAOne(
        displayName = "Last Message", 
        isCalculated = true, 
        calcDependentProperties = {P_ChatMessages}, 
        reverseName = ChatMessage.P_CalcChatSession, 
        allowCreateNew = false, 
        allowAddExisting = false
    )
    public ChatMessage getCalcLastChatMessage() {
        return getChatMessages().getAt(0);
    }

    @OAMany(
        displayName = "Chat Messages", 
        toClass = ChatMessage.class, 
        owner = true, 
        reverseName = ChatMessage.P_ChatSession, 
        cascadeSave = true, 
        cascadeDelete = true
    )
    public Hub<ChatMessage> getChatMessages() {
        if (hubChatMessages == null) {
            hubChatMessages = (Hub<ChatMessage>) getHub(P_ChatMessages);
        }
        return hubChatMessages;
    }

    @OAMany(
        toClass = User.class, 
        reverseName = User.P_ChatSessions
    )
    @OALinkTable(name = "ChatSessionUserTable", indexName = "UserTableChatSession", columns = {"ChatSessionId"})
    public Hub<User> getUsers() {
        if (hubUsers == null) {
            hubUsers = (Hub<User>) getHub(P_Users);
        }
        return hubUsers;
    }
}
 
