// Generated by OABuilder
package com.cdi.model.oa;
 
import java.util.*;
import java.util.logging.*;
import java.sql.*;
import com.viaoa.util.*;
import com.viaoa.object.*;
import com.viaoa.schedule.*;
import com.viaoa.hub.*;
import com.viaoa.lang.OAString;
import com.viaoa.annotation.*;
import com.viaoa.callback.OAObjectCallback;
import com.cdi.delegate.oa.*;
import com.cdi.model.oa.filter.*;
import com.cdi.model.oa.propertypath.*;
 
@OAClass(
    lowerName = "contact",
    pluralName = "Contacts",
    shortName = "con",
    displayName = "Contact",
    displayProperty = "name",
    sortProperty = "name",
    noPojo = true
)
@OATable(
    indexes = {
        @OAIndex(name = "ContactLoginId", columns = {@OAIndexColumn(name = "LoginId", lowerName = "LoginIdLower")}),
        @OAIndex(name = "ContactCustomer", fkey = true, columns = { @OAIndexColumn(name = "CustomerId") })
    }
)
public class Contact extends OAObject {
    private static final long serialVersionUID = 1L;
    private static Logger LOG = Logger.getLogger(Contact.class.getName());

    public static final String P_Id = "id";
    public static final String P_Name = "name";
    public static final String P_Title = "title";
    public static final String P_Email = "email";
    public static final String P_Notes = "notes";
    public static final String P_LoginId = "loginId";
    public static final String P_Password = "password";
     
    public static final String P_Customer = "customer";
    public static final String P_CustomerId = "customerId"; // fkey
    public static final String P_OrderContacts = "orderContacts";
    public static final String P_Phones = "phones";
     
    protected volatile int id;
    protected volatile String name;
    protected volatile String title;
    protected volatile String email;
    protected volatile String notes;
    protected volatile String loginId;
    protected volatile String password;
     
    // Links to other objects.
    protected volatile transient Customer customer;
    protected transient Hub<OrderContact> hubOrderContacts;
    protected transient Hub<Phone> hubPhones;
     
    public Contact() {
        if (!isLoading()) setObjectDefaults();
    }
     
    public Contact(int id) {
        this();
        setId(id);
    }

    @OAProperty(lowerName = "id", isUnique = true, displayLength = 6)
    @OAId
    @OAColumn(name = "Id", sqlType = java.sql.Types.INTEGER)
    public int getId() {
        return id;
    }
    public void setId(int newValue) {
        int old = id;
        fireBeforePropertyChange(P_Id, old, newValue);
        this.id = newValue;
        firePropertyChange(P_Id, old, this.id);
    }

    @OAProperty(lowerName = "name", maxLength = 70, displayLength = 20, uiColumnLength = 15)
    @OAColumn(name = "Name", maxLength = 70)
    public String getName() {
        return name;
    }
    public void setName(String newValue) {
        String old = name;
        fireBeforePropertyChange(P_Name, old, newValue);
        this.name = newValue;
        firePropertyChange(P_Name, old, this.name);
    }

    @OAProperty(lowerName = "title", maxLength = 55, displayLength = 20, uiColumnLength = 15)
    @OAColumn(name = "Title", maxLength = 55)
    public String getTitle() {
        return title;
    }
    public void setTitle(String newValue) {
        String old = title;
        fireBeforePropertyChange(P_Title, old, newValue);
        this.title = newValue;
        firePropertyChange(P_Title, old, this.title);
    }

    @OAProperty(lowerName = "email", maxLength = 65, displayLength = 20, uiColumnLength = 15, isEmail = true)
    @OAColumn(name = "Email", maxLength = 65)
    public String getEmail() {
        return email;
    }
    public void setEmail(String newValue) {
        String old = email;
        fireBeforePropertyChange(P_Email, old, newValue);
        this.email = newValue;
        firePropertyChange(P_Email, old, this.email);
    }

    @OAProperty(lowerName = "notes", displayLength = 20, hasCustomCode = true, isHtml = true)
    @OAColumn(name = "Notes", sqlType = java.sql.Types.CLOB)
    public String getNotes() {
        if (notes != null) notes = OAString.convertTextToHtml(notes, false);
        return notes;
    }
    public void setNotes(String newValue) {
        String old = notes;
        fireBeforePropertyChange(P_Notes, old, newValue);
        this.notes = newValue;
        firePropertyChange(P_Notes, old, this.notes);
    }

    @OAProperty(lowerName = "loginId", displayName = "Login Id", maxLength = 55, displayLength = 15, uiColumnLength = 14)
    @OAColumn(name = "LoginId", maxLength = 55, lowerName = "LoginIdLower")
    public String getLoginId() {
        return loginId;
    }
    public void setLoginId(String newValue) {
        String old = loginId;
        fireBeforePropertyChange(P_LoginId, old, newValue);
        this.loginId = newValue;
        firePropertyChange(P_LoginId, old, this.loginId);
    }
     
    @OAObjCallback(visibleProperty = Contact.P_Customer+"."+Customer.P_AllowUserAccess)
    public void loginIdCallback(OAObjectCallback callback) {
        if (callback == null) return;
        switch (callback.getType()) {
        }
    }

    @OAProperty(lowerName = "password", maxLength = 55, displayLength = 15, isSHAHash = true)
    @OAColumn(name = "Password", maxLength = 55)
    public String getPassword() {
        return password;
    }
    public void setPassword(String newValue) {
        String old = password;
        fireBeforePropertyChange(P_Password, old, newValue);
        this.password = newValue;
        firePropertyChange(P_Password, old, this.password);
    }
     
    @OAObjCallback(visibleProperty = Contact.P_Customer+"."+Customer.P_AllowUserAccess)
    public void passwordCallback(OAObjectCallback callback) {
        if (callback == null) return;
        switch (callback.getType()) {
        }
    }

    @OAOne(
        reverseName = Customer.P_Contacts, 
        required = true, 
        allowCreateNew = false, 
        fkeys = {@OAFkey(fromProperty = P_CustomerId, toProperty = Customer.P_Id)}
    )
    public Customer getCustomer() {
        if (customer == null) {
            customer = (Customer) getObject(P_Customer);
        }
        return customer;
    }
    public void setCustomer(Customer newValue) {
        Customer old = this.customer;
        fireBeforePropertyChange(P_Customer, old, newValue);
        this.customer = newValue;
        firePropertyChange(P_Customer, old, this.customer);
    }
    @OAProperty(isFkeyOnly = true)
    @OAColumn(name = "CustomerId")
    public Integer getCustomerId() {
        return (Integer) getFkeyProperty(P_CustomerId);
    }
    public void setCustomerId(Integer newValue) {
        this.customer = null;
        setFkeyProperty(P_CustomerId, newValue);
    }

    @OAMany(
        displayName = "Order Contacts", 
        toClass = OrderContact.class, 
        reverseName = OrderContact.P_Contact
    )
    public Hub<OrderContact> getOrderContacts() {
        if (hubOrderContacts == null) {
            hubOrderContacts = (Hub<OrderContact>) getHub(P_OrderContacts);
        }
        return hubOrderContacts;
    }

    @OAMany(
        toClass = Phone.class, 
        owner = true, 
        reverseName = Phone.P_Contact, 
        cascadeSave = true, 
        cascadeDelete = true
    )
    public Hub<Phone> getPhones() {
        if (hubPhones == null) {
            hubPhones = (Hub<Phone>) getHub(P_Phones);
        }
        return hubPhones;
    }
    public void load(ResultSet rs, int id) throws SQLException {
        this.id = id;
        this.name = rs.getString(2);
        this.title = rs.getString(3);
        this.email = rs.getString(4);
        this.notes = rs.getString(5);
        this.loginId = rs.getString(6);
        this.password = rs.getString(7);
        int customerFkey = rs.getInt(8);
        setFkeyProperty(P_Customer, rs.wasNull() ? null : customerFkey);

        this.changedFlag = false;
        this.newFlag = false;
    }
}
 
