// Generated by OABuilder
package com.cdi.model.oa;
 
import java.util.*;
import java.util.logging.*;
import java.sql.*;
import com.viaoa.object.*;
import com.viaoa.schedule.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.annotation.*;
import com.cdi.delegate.oa.*;
import com.cdi.model.oa.filter.*;
import com.cdi.model.oa.propertypath.*;
 
@OAClass(
    lowerName = "country",
    pluralName = "Countries",
    shortName = "cou",
    displayName = "Country",
    isLookup = true,
    isPreSelect = true,
    displayProperty = "displayName",
    sortProperty = "code",
    noPojo = true
)
@OATable(
)
public class Country extends OAObject {
    private static final long serialVersionUID = 1L;
    private static Logger LOG = Logger.getLogger(Country.class.getName());

    public static final String P_Id = "id";
    public static final String P_Code = "code";
    public static final String P_Name = "name";
     
    public static final String P_DisplayName = "displayName";
     
    protected volatile int id;
    protected volatile String code;
    protected volatile String name;
     
    public Country() {
        if (!isLoading()) setObjectDefaults();
    }
     
    public Country(int id) {
        this();
        setId(id);
    }

    @OAProperty(lowerName = "id", isUnique = true, displayLength = 6)
    @OAId
    @OAColumn(name = "Id", sqlType = java.sql.Types.INTEGER)
    public int getId() {
        return id;
    }
    public void setId(int newValue) {
        int old = id;
        fireBeforePropertyChange(P_Id, old, newValue);
        this.id = newValue;
        firePropertyChange(P_Id, old, this.id);
    }

    @OAProperty(lowerName = "code", maxLength = 15, displayLength = 10)
    @OAColumn(name = "Code", maxLength = 15)
    public String getCode() {
        return code;
    }
    public void setCode(String newValue) {
        String old = code;
        fireBeforePropertyChange(P_Code, old, newValue);
        this.code = newValue;
        firePropertyChange(P_Code, old, this.code);
    }

    @OAProperty(lowerName = "name", maxLength = 65, displayLength = 20, uiColumnLength = 12)
    @OAColumn(name = "Name", maxLength = 65)
    public String getName() {
        return name;
    }
    public void setName(String newValue) {
        String old = name;
        fireBeforePropertyChange(P_Name, old, newValue);
        this.name = newValue;
        firePropertyChange(P_Name, old, this.name);
    }
    @OACalculatedProperty(displayName = "Display Name", displayLength = 20, columnLength = 15, properties = {P_Code, P_Name})
    public String getDisplayName() {
        String s = name;
        if (s == null) s = "";    
        if (code != null && code.length() > 0) s += " (" + code + ")";
        return s;
    }
    public void load(ResultSet rs, int id) throws SQLException {
        this.id = id;
        this.code = rs.getString(2);
        this.name = rs.getString(3);

        this.changedFlag = false;
        this.newFlag = false;
    }
}
 
