// Generated by OABuilder
package com.cdi.model.oa;
 
import java.util.*;
import java.util.logging.*;
import java.sql.*;
import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.scheduler.*;
import com.viaoa.util.*;
import com.viaoa.annotation.*;
import com.viaoa.util.OADateTime;
import com.cdi.delegate.oa.*;
import com.cdi.model.oa.filter.*;
import com.cdi.model.oa.propertypath.*;
import com.viaoa.func.OAFunction;
 
@OAClass(
    lowerName = "openOrderItem",
    pluralName = "OpenOrderItems",
    shortName = "ooi",
    displayName = "Open Order Item",
    useDataSource = false,
    isProcessed = true,
    displayProperty = "item",
    filterClasses = {OpenOrderItemHasOpenOrderItemsFilter.class},
    noPojo = true
)
public class OpenOrderItem extends OAObject {
    private static final long serialVersionUID = 1L;
    private static Logger LOG = Logger.getLogger(OpenOrderItem.class.getName());

    public static final String P_Id = "id";
    public static final String P_Created = "created";
     
    public static final String P_OrderCount = "orderCount";
    public static final String P_TotalRemainingQuantity = "totalRemainingQuantity";
    public static final String P_TotalRemainingDays = "totalRemainingDays";
     
    public static final String P_Item = "item";
    public static final String P_ItemId = "itemId"; // fkey
    public static final String P_OpenOrderItems = "openOrderItems";
     
    protected volatile int id;
    protected volatile OADateTime created;
     
    // Links to other objects.
    protected volatile transient Item item;
    protected transient Hub<OrderItem> hubOpenOrderItems;
     
    public OpenOrderItem() {
        if (!isLoading()) setObjectDefaults();
    }
    @Override
    public void setObjectDefaults() {
        setCreated(new OADateTime());
    }
     
    public OpenOrderItem(int id) {
        this();
        setId(id);
    }

    @OAProperty(lowerName = "id", isUnique = true, trackPrimitiveNull = false, displayLength = 6)
    @OAId
    @OAColumn(name = "Id", sqlType = java.sql.Types.INTEGER)
    public int getId() {
        return id;
    }
    public void setId(int newValue) {
        int old = id;
        fireBeforePropertyChange(P_Id, old, newValue);
        this.id = newValue;
        firePropertyChange(P_Id, old, this.id);
    }

    @OAProperty(lowerName = "created", defaultValue = "new OADateTime()", displayLength = 15, isProcessed = true, ignoreTimeZone = true)
    @OAColumn(name = "Created", sqlType = java.sql.Types.TIMESTAMP)
    public OADateTime getCreated() {
        return created;
    }
    public void setCreated(OADateTime newValue) {
        OADateTime old = created;
        fireBeforePropertyChange(P_Created, old, newValue);
        this.created = newValue;
        firePropertyChange(P_Created, old, this.created);
    }
    @OACalculatedProperty(displayName = "Order Count", displayLength = 6, columnName = "Orders", properties = {P_OpenOrderItems})
    public int getOrderCount() {
         return getOpenOrderItems().size();
    }
    @OACalculatedProperty(displayName = "Remaining Qty", displayLength = 6, columnLength = 10, columnName = "Remain Qty", properties = {P_OpenOrderItems})
    public int getTotalRemainingQuantity() {
        int x = (int) OAFunction.sum(getOpenOrderItems(), OrderItem.P_RemainingQuantity);
        return x;
    }
    @OACalculatedProperty(displayName = "Remaining Days", displayLength = 6, columnLength = 11, columnName = "Remain Days", properties = {P_OrderCount, P_Item+"."+Item.P_Mold+"."+Mold.P_OnHand})
    public int getTotalRemainingDays() {
        int qty = (int) OAFunction.sum(getOpenOrderItems(), OrderItem.P_RemainingQuantity);
        if (qty <= 0) return 0;
        
        Item item = getItem();
        if (item == null) return 99;
    
        Mold mold = item.getMold();
        if (mold == null) return 99;
        
        int onHand = mold.getOnHand();
        if (onHand <= 0) return 99;
    
        int days = (int) Math.ceil( qty / ((double)onHand));
        return days;
    }

    @OAOne(
        reverseName = Item.P_OpenOrderItem, 
        allowCreateNew = false, 
        allowAddExisting = false, 
        fkeys = {@OAFkey(fromProperty = P_ItemId, toProperty = Item.P_Id)}
    )
    public Item getItem() {
        if (item == null) {
            item = (Item) getObject(P_Item);
        }
        return item;
    }
    public void setItem(Item newValue) {
        Item old = this.item;
        fireBeforePropertyChange(P_Item, old, newValue);
        this.item = newValue;
        firePropertyChange(P_Item, old, this.item);
    }
    @OAProperty(isFkeyOnly = true)
    @OAColumn(name = "ItemId")
    public Integer getItemId() {
        return (Integer) getFkeyProperty(P_ItemId);
    }
    public void setItemId(Integer newValue) {
        this.item = null;
        setFkeyProperty(P_ItemId, newValue);
    }

    @OAMany(
        displayName = "Open Order Items", 
        toClass = OrderItem.class, 
        isCalculated = true, 
        isServerSideCalc = true, 
        reverseName = OrderItem.P_GroupByOpenOrderItems, 
        isProcessed = true
    )
    public Hub<OrderItem> getOpenOrderItems() {
        if (hubOpenOrderItems == null) {
            hubOpenOrderItems = (Hub<OrderItem>) getHub(P_OpenOrderItems);
        }
        return hubOpenOrderItems;
    }
}
 
