// Generated by OABuilder
package com.cdi.model.oa;
 
import java.util.*;
import java.util.logging.*;
import java.sql.*;
import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.scheduler.*;
import com.viaoa.util.*;
import com.viaoa.annotation.*;
import com.cdi.delegate.oa.*;
import com.cdi.model.oa.filter.*;
import com.cdi.model.oa.propertypath.*;
 
@OAClass(
    lowerName = "orderItemComment",
    pluralName = "OrderItemComments",
    shortName = "oic",
    displayName = "Order Item Comment",
    displayProperty = "orderItem.order",
    sortProperty = "orderItem.order",
    noPojo = true
)
@OATable(
    indexes = {
        @OAIndex(name = "OrderItemCommentOrderItem", fkey = true, columns = { @OAIndexColumn(name = "OrderItemId") })
    }
)
public class OrderItemComment extends OAObject {
    private static final long serialVersionUID = 1L;
    private static Logger LOG = Logger.getLogger(OrderItemComment.class.getName());

    public static final String P_Id = "id";
    public static final String P_Description = "description";
     
    public static final String P_OrderItem = "orderItem";
    public static final String P_OrderItemId = "orderItemId"; // fkey
     
    protected volatile int id;
    protected volatile String description;
     
    // Links to other objects.
    protected volatile transient OrderItem orderItem;
     
    public OrderItemComment() {
        if (!isLoading()) setObjectDefaults();
    }
     
    public OrderItemComment(int id) {
        this();
        setId(id);
    }

    @OAProperty(lowerName = "id", isUnique = true, displayLength = 6)
    @OAId
    @OAColumn(name = "Id", sqlType = java.sql.Types.INTEGER)
    public int getId() {
        return id;
    }
    public void setId(int newValue) {
        int old = id;
        fireBeforePropertyChange(P_Id, old, newValue);
        this.id = newValue;
        firePropertyChange(P_Id, old, this.id);
    }

    @OAProperty(lowerName = "description", maxLength = 254, displayLength = 20)
    @OAColumn(name = "Description", maxLength = 254)
    public String getDescription() {
        return description;
    }
    public void setDescription(String newValue) {
        String old = description;
        fireBeforePropertyChange(P_Description, old, newValue);
        this.description = newValue;
        firePropertyChange(P_Description, old, this.description);
    }

    @OAOne(
        displayName = "Order Item", 
        reverseName = OrderItem.P_OrderItemComments, 
        required = true, 
        allowCreateNew = false, 
        fkeys = {@OAFkey(fromProperty = P_OrderItemId, toProperty = OrderItem.P_Id)}
    )
    public OrderItem getOrderItem() {
        if (orderItem == null) {
            orderItem = (OrderItem) getObject(P_OrderItem);
        }
        return orderItem;
    }
    public void setOrderItem(OrderItem newValue) {
        OrderItem old = this.orderItem;
        fireBeforePropertyChange(P_OrderItem, old, newValue);
        this.orderItem = newValue;
        firePropertyChange(P_OrderItem, old, this.orderItem);
    }
    @OAProperty(isFkeyOnly = true)
    @OAColumn(name = "OrderItemId")
    public Integer getOrderItemId() {
        return (Integer) getFkeyProperty(P_OrderItemId);
    }
    public void setOrderItemId(Integer newValue) {
        this.orderItem = null;
        setFkeyProperty(P_OrderItemId, newValue);
    }
    public void load(ResultSet rs, int id) throws SQLException {
        this.id = id;
        this.description = rs.getString(2);
        int orderItemFkey = rs.getInt(3);
        setFkeyProperty(P_OrderItem, rs.wasNull() ? null : orderItemFkey);

        this.changedFlag = false;
        this.newFlag = false;
    }
}
 
