// Generated by OABuilder
package com.cdi.model.oa;
 
import java.util.*;
import java.util.logging.*;
import java.sql.*;
import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.scheduler.*;
import com.viaoa.util.*;
import com.viaoa.annotation.*;
import com.cdi.delegate.oa.*;
import com.cdi.model.oa.filter.*;
import com.cdi.model.oa.propertypath.*;
 
@OAClass(
    lowerName = "phone",
    pluralName = "Phones",
    shortName = "pho",
    displayName = "Phone",
    displayProperty = "number",
    sortProperty = "number",
    noPojo = true
)
@OATable(
    indexes = {
        @OAIndex(name = "PhoneContact", fkey = true, columns = { @OAIndexColumn(name = "ContactId") })
    }
)
public class Phone extends OAObject {
    private static final long serialVersionUID = 1L;
    private static Logger LOG = Logger.getLogger(Phone.class.getName());

    public static final String P_Id = "id";
    public static final String P_Number = "number";
    public static final String P_Notes = "notes";
     
    public static final String P_Contact = "contact";
    public static final String P_ContactId = "contactId"; // fkey
     
    protected volatile int id;
    protected volatile String number;
    protected volatile String notes;
     
    // Links to other objects.
    protected volatile transient Contact contact;
     
    public Phone() {
        if (!isLoading()) setObjectDefaults();
    }
     
    public Phone(int id) {
        this();
        setId(id);
    }

    @OAProperty(lowerName = "id", isUnique = true, displayLength = 6)
    @OAId
    @OAColumn(name = "Id", sqlType = java.sql.Types.INTEGER)
    public int getId() {
        return id;
    }
    public void setId(int newValue) {
        int old = id;
        fireBeforePropertyChange(P_Id, old, newValue);
        this.id = newValue;
        firePropertyChange(P_Id, old, this.id);
    }

    @OAProperty(lowerName = "number", maxLength = 25, displayLength = 10, isPhone = true)
    @OAColumn(name = "Number", maxLength = 25)
    public String getNumber() {
        return number;
    }
    public void setNumber(String newValue) {
        String old = number;
        fireBeforePropertyChange(P_Number, old, newValue);
        this.number = newValue;
        firePropertyChange(P_Number, old, this.number);
    }

    @OAProperty(lowerName = "notes", maxLength = 250, displayLength = 15, uiColumnLength = 13)
    @OAColumn(name = "Notes", maxLength = 250)
    public String getNotes() {
        return notes;
    }
    public void setNotes(String newValue) {
        String old = notes;
        fireBeforePropertyChange(P_Notes, old, newValue);
        this.notes = newValue;
        firePropertyChange(P_Notes, old, this.notes);
    }

    @OAOne(
        reverseName = Contact.P_Phones, 
        required = true, 
        allowCreateNew = false, 
        fkeys = {@OAFkey(fromProperty = P_ContactId, toProperty = Contact.P_Id)}
    )
    public Contact getContact() {
        if (contact == null) {
            contact = (Contact) getObject(P_Contact);
        }
        return contact;
    }
    public void setContact(Contact newValue) {
        Contact old = this.contact;
        fireBeforePropertyChange(P_Contact, old, newValue);
        this.contact = newValue;
        firePropertyChange(P_Contact, old, this.contact);
    }
    @OAProperty(isFkeyOnly = true)
    @OAColumn(name = "ContactId")
    public Integer getContactId() {
        return (Integer) getFkeyProperty(P_ContactId);
    }
    public void setContactId(Integer newValue) {
        this.contact = null;
        setFkeyProperty(P_ContactId, newValue);
    }
    public void load(ResultSet rs, int id) throws SQLException {
        this.id = id;
        this.number = rs.getString(2);
        this.notes = rs.getString(3);
        int contactFkey = rs.getInt(4);
        setFkeyProperty(P_Contact, rs.wasNull() ? null : contactFkey);

        this.changedFlag = false;
        this.newFlag = false;
    }
}
 
