// Generated by OABuilder
package com.cdi.model.oa;
 
import java.util.*;
import java.util.logging.*;
import java.sql.*;
import com.viaoa.util.*;
import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.scheduler.*;
import com.viaoa.annotation.*;
import com.viaoa.util.OADateTime;
import com.cdi.delegate.oa.*;
import com.cdi.model.oa.filter.*;
import com.cdi.model.oa.propertypath.*;
 
@OAClass(
    lowerName = "quickbook",
    pluralName = "Quickbooks",
    shortName = "qb",
    displayName = "Quickbook",
    estimatedTotal = 1,
    singleton = true,
    pojoSingleton = true,
    noPojo = true
)
@OATable(
)
public class Quickbook extends OAObject {
    private static final long serialVersionUID = 1L;
    private static Logger LOG = Logger.getLogger(Quickbook.class.getName());

    public static final String P_Id = "id";
    public static final String P_Started = "started";
    public static final String P_Enabled = "enabled";
    public static final String P_CurrentStep = "currentStep";
    public static final String P_CurrentStepString = "currentStepString";
    public static final String P_CurrentStepEnum = "currentStepEnum";
    public static final String P_CurrentStepDisplay = "currentStepDisplay";
    public static final String P_TsCurrentStep = "tsCurrentStep";
    public static final String P_AllowSendOrders = "allowSendOrders";
    public static final String P_AllowGetOrders = "allowGetOrders";
    public static final String P_AllowUpdateOrders = "allowUpdateOrders";
    public static final String P_AllowDisableOrders = "allowDisableOrders";
    public static final String P_AllowItemAdjustments = "allowItemAdjustments";
    public static final String P_AllowUpdateCustomers = "allowUpdateCustomers";
    public static final String P_AllowDisableCustomers = "allowDisableCustomers";
    public static final String P_AllowUpdateItems = "allowUpdateItems";
    public static final String P_AllowDisableItems = "allowDisableItems";
    public static final String P_AllowUpdateCustomersNow = "allowUpdateCustomersNow";
    public static final String P_AllowUpdateItemsNow = "allowUpdateItemsNow";
    public static final String P_LastUpdated = "lastUpdated";
    public static final String P_LastGetOrders = "lastGetOrders";
    public static final String P_QbwcLastCalled = "qbwcLastCalled";
    public static final String P_Console = "console";
    public static final String P_WarningConsole = "warningConsole";
    public static final String P_QbwcConsole = "qbwcConsole";
    public static final String P_FinerConsole = "finerConsole";
     
    protected volatile int id;
    protected volatile OADateTime started;
    protected volatile boolean enabled;
    protected volatile int currentStep;

    public static enum CurrentStep {
        Unknown("Unknown"),
        SendSubmittedOrders("Send Submitted Orders"),
        GetNewChangedQbOrders("Get New/Changed QB Orders"),
        InventoryAdjustments("Inventory Adjustments"),
        UpdateChangedItems("Update Changed Items"),
        UpdateServiceItems("Update Service Items"),
        UpdateCustomers("Update Customers"),
        UpdateOrders("Update Orders"),
        UpdateAllItems("Update All Items"),
        UpdateAllCustomers("Update All Customers"),
        SleepingOneMinute("Sleeping One Minute");

        private String display;
        CurrentStep(String display) {
            this.display = display;
        }

        public String getDisplay() {
            return display;
        }
    }
    public static final int CURRENTSTEP_Unknown = 0;
    public static final int CURRENTSTEP_SendSubmittedOrders = 1;
    public static final int CURRENTSTEP_GetNewChangedQbOrders = 2;
    public static final int CURRENTSTEP_InventoryAdjustments = 3;
    public static final int CURRENTSTEP_UpdateChangedItems = 4;
    public static final int CURRENTSTEP_UpdateServiceItems = 5;
    public static final int CURRENTSTEP_UpdateCustomers = 6;
    public static final int CURRENTSTEP_UpdateOrders = 7;
    public static final int CURRENTSTEP_UpdateAllItems = 8;
    public static final int CURRENTSTEP_UpdateAllCustomers = 9;
    public static final int CURRENTSTEP_SleepingOneMinute = 10;

    protected volatile OADateTime tsCurrentStep;
    protected volatile boolean allowSendOrders;
    protected volatile boolean allowGetOrders;
    protected volatile boolean allowUpdateOrders;
    protected volatile boolean allowDisableOrders;
    protected volatile boolean allowItemAdjustments;
    protected volatile boolean allowUpdateCustomers;
    protected volatile boolean allowDisableCustomers;
    protected volatile boolean allowUpdateItems;
    protected volatile boolean allowDisableItems;
    protected volatile boolean allowUpdateCustomersNow;
    protected volatile boolean allowUpdateItemsNow;
    protected volatile OADateTime lastUpdated;
    protected volatile OADateTime lastGetOrders;
    protected volatile OADateTime qbwcLastCalled;
    protected volatile String console;
    protected volatile String warningConsole;
    protected volatile String qbwcConsole;
    protected volatile String finerConsole;
     
    public Quickbook() {
        if (!isLoading()) setObjectDefaults();
    }
     
    public Quickbook(int id) {
        this();
        setId(id);
    }

    @OAProperty(lowerName = "id", isUnique = true, displayLength = 6)
    @OAId
    @OAColumn(name = "Id", sqlType = java.sql.Types.INTEGER)
    public int getId() {
        return id;
    }
    public void setId(int newValue) {
        int old = id;
        fireBeforePropertyChange(P_Id, old, newValue);
        this.id = newValue;
        firePropertyChange(P_Id, old, this.id);
    }

    @OAProperty(lowerName = "started", displayLength = 15, isProcessed = true, ignoreTimeZone = true)
    @OAColumn(name = "Started", sqlType = java.sql.Types.TIMESTAMP)
    public OADateTime getStarted() {
        return started;
    }
    public void setStarted(OADateTime newValue) {
        OADateTime old = started;
        fireBeforePropertyChange(P_Started, old, newValue);
        this.started = newValue;
        firePropertyChange(P_Started, old, this.started);
    }

    @OAProperty(lowerName = "enabled", displayLength = 5, uiColumnLength = 7)
    @OAColumn(name = "Enabled", sqlType = java.sql.Types.BOOLEAN)
    public boolean getEnabled() {
        return enabled;
    }
    public boolean isEnabled() {
        return getEnabled();
    }
    public void setEnabled(boolean newValue) {
        boolean old = enabled;
        fireBeforePropertyChange(P_Enabled, old, newValue);
        this.enabled = newValue;
        firePropertyChange(P_Enabled, old, this.enabled);
    }

    @OAProperty(lowerName = "currentStep", displayName = "Current Step", trackPrimitiveNull = false, displayLength = 6, uiColumnLength = 12, hasCustomCode = true, isProcessed = true, isNameValue = true)
    @OAColumn(name = "CurrentStep", sqlType = java.sql.Types.INTEGER)
    public int getCurrentStep() {
        return currentStep;
    }
    public void setCurrentStep(int newValue) {
        int old = currentStep;
        fireBeforePropertyChange(P_CurrentStep, old, newValue);
        this.currentStep = newValue;
        firePropertyChange(P_CurrentStep, old, this.currentStep);
        if (!isLoading() && isServer()) setTsCurrentStep(new OADateTime());
    }

    @OAProperty(enumPropertyName = P_CurrentStep)
    public String getCurrentStepString() {
        CurrentStep currentStep = getCurrentStepEnum();
        if (currentStep == null) return null;
        return currentStep.name();
    }
    public void setCurrentStepString(String val) {
        int x = -1;
        if (OAString.isNotEmpty(val)) {
            CurrentStep currentStep = CurrentStep.valueOf(val);
            if (currentStep != null) x = currentStep.ordinal();
        }
        if (x < 0) x = 0;
        setCurrentStep(x);
    }
    @OAProperty(enumPropertyName = P_CurrentStep)
    public CurrentStep getCurrentStepEnum() {
        final int val = getCurrentStep();
        if (val < 0 || val >= CurrentStep.values().length) return null;
        return CurrentStep.values()[val];
    }
    public void setCurrentStepEnum(CurrentStep val) {
        if (val == null) {
            setCurrentStep(0);
        }
        else {
            setCurrentStep(val.ordinal());
        }
    }
    @OACalculatedProperty(enumPropertyName = P_CurrentStep, displayName = "Current Step", displayLength = 6, columnLength = 12, properties = {P_CurrentStep} )
    public String getCurrentStepDisplay() {
        CurrentStep currentStep = getCurrentStepEnum();
        if (currentStep == null) return null;
        return currentStep.getDisplay();
    }

    @OAProperty(lowerName = "tsCurrentStep", displayName = "ts Current Step", displayLength = 15, ignoreTimeZone = true)
    @OAColumn(name = "TsCurrentStep", sqlType = java.sql.Types.TIMESTAMP)
    public OADateTime getTsCurrentStep() {
        return tsCurrentStep;
    }
    public void setTsCurrentStep(OADateTime newValue) {
        OADateTime old = tsCurrentStep;
        fireBeforePropertyChange(P_TsCurrentStep, old, newValue);
        this.tsCurrentStep = newValue;
        firePropertyChange(P_TsCurrentStep, old, this.tsCurrentStep);
    }

    @OAProperty(lowerName = "allowSendOrders", displayName = "Allow Send Orders", description = "send submitted Sales Orders to QB", displayLength = 5, uiColumnLength = 17)
    @OAColumn(name = "AllowSendOrders", sqlType = java.sql.Types.BOOLEAN)
    /**
      send submitted Sales Orders to QB
    */
    public boolean getAllowSendOrders() {
        return allowSendOrders;
    }
    public boolean isAllowSendOrders() {
        return getAllowSendOrders();
    }
    public void setAllowSendOrders(boolean newValue) {
        boolean old = allowSendOrders;
        fireBeforePropertyChange(P_AllowSendOrders, old, newValue);
        this.allowSendOrders = newValue;
        firePropertyChange(P_AllowSendOrders, old, this.allowSendOrders);
    }

    @OAProperty(lowerName = "allowGetOrders", displayName = "Allow Get Orders", description = "get QB Orders and create Order & WorkOrder", displayLength = 5, uiColumnLength = 16)
    @OAColumn(name = "AllowGetOrders", sqlType = java.sql.Types.BOOLEAN)
    /**
      get QB Orders and create Order & WorkOrder
    */
    public boolean getAllowGetOrders() {
        return allowGetOrders;
    }
    public boolean isAllowGetOrders() {
        return getAllowGetOrders();
    }
    public void setAllowGetOrders(boolean newValue) {
        boolean old = allowGetOrders;
        fireBeforePropertyChange(P_AllowGetOrders, old, newValue);
        this.allowGetOrders = newValue;
        firePropertyChange(P_AllowGetOrders, old, this.allowGetOrders);
    }

    @OAProperty(lowerName = "allowUpdateOrders", displayName = "Allow Update Orders", description = "update Orders with QB orders", displayLength = 5, uiColumnLength = 19)
    @OAColumn(name = "AllowUpdateOrders", sqlType = java.sql.Types.BOOLEAN)
    /**
      update Orders with QB orders
    */
    public boolean getAllowUpdateOrders() {
        return allowUpdateOrders;
    }
    public boolean isAllowUpdateOrders() {
        return getAllowUpdateOrders();
    }
    public void setAllowUpdateOrders(boolean newValue) {
        boolean old = allowUpdateOrders;
        fireBeforePropertyChange(P_AllowUpdateOrders, old, newValue);
        this.allowUpdateOrders = newValue;
        firePropertyChange(P_AllowUpdateOrders, old, this.allowUpdateOrders);
    }

    @OAProperty(lowerName = "allowDisableOrders", displayName = "Allow Disable Orders", description = "ok to disable orders that have been deleted from QB?", displayLength = 5, uiColumnLength = 20)
    @OAColumn(name = "AllowDisableOrders", sqlType = java.sql.Types.BOOLEAN)
    /**
      ok to disable orders that have been deleted from QB?
    */
    public boolean getAllowDisableOrders() {
        return allowDisableOrders;
    }
    public boolean isAllowDisableOrders() {
        return getAllowDisableOrders();
    }
    public void setAllowDisableOrders(boolean newValue) {
        boolean old = allowDisableOrders;
        fireBeforePropertyChange(P_AllowDisableOrders, old, newValue);
        this.allowDisableOrders = newValue;
        firePropertyChange(P_AllowDisableOrders, old, this.allowDisableOrders);
    }

    @OAProperty(lowerName = "allowItemAdjustments", displayName = "Allow Item Adjustments", description = "send OrderItem on Hand changes to QB", displayLength = 5, uiColumnLength = 22)
    @OAColumn(name = "AllowItemAdjustments", sqlType = java.sql.Types.BOOLEAN)
    /**
      send OrderItem on Hand changes to QB
    */
    public boolean getAllowItemAdjustments() {
        return allowItemAdjustments;
    }
    public boolean isAllowItemAdjustments() {
        return getAllowItemAdjustments();
    }
    public void setAllowItemAdjustments(boolean newValue) {
        boolean old = allowItemAdjustments;
        fireBeforePropertyChange(P_AllowItemAdjustments, old, newValue);
        this.allowItemAdjustments = newValue;
        firePropertyChange(P_AllowItemAdjustments, old, this.allowItemAdjustments);
    }

    @OAProperty(lowerName = "allowUpdateCustomers", displayName = "Allow Update Customers", description = "update customers from QB", displayLength = 5, uiColumnLength = 22)
    @OAColumn(name = "AllowUpdateCustomers", sqlType = java.sql.Types.BOOLEAN)
    /**
      update customers from QB
    */
    public boolean getAllowUpdateCustomers() {
        return allowUpdateCustomers;
    }
    public boolean isAllowUpdateCustomers() {
        return getAllowUpdateCustomers();
    }
    public void setAllowUpdateCustomers(boolean newValue) {
        boolean old = allowUpdateCustomers;
        fireBeforePropertyChange(P_AllowUpdateCustomers, old, newValue);
        this.allowUpdateCustomers = newValue;
        firePropertyChange(P_AllowUpdateCustomers, old, this.allowUpdateCustomers);
    }

    @OAProperty(lowerName = "allowDisableCustomers", displayName = "Allow Disable Customers", description = "ok to disable customers that are not in quickbooks", displayLength = 5, uiColumnLength = 23)
    @OAColumn(name = "AllowDisableCustomers", sqlType = java.sql.Types.BOOLEAN)
    /**
      ok to disable customers that are not in quickbooks
    */
    public boolean getAllowDisableCustomers() {
        return allowDisableCustomers;
    }
    public boolean isAllowDisableCustomers() {
        return getAllowDisableCustomers();
    }
    public void setAllowDisableCustomers(boolean newValue) {
        boolean old = allowDisableCustomers;
        fireBeforePropertyChange(P_AllowDisableCustomers, old, newValue);
        this.allowDisableCustomers = newValue;
        firePropertyChange(P_AllowDisableCustomers, old, this.allowDisableCustomers);
    }

    @OAProperty(lowerName = "allowUpdateItems", displayName = "Allow Update Items", description = "update Items from QB", displayLength = 5, uiColumnLength = 18)
    @OAColumn(name = "AllowUpdateItems", sqlType = java.sql.Types.BOOLEAN)
    /**
      update Items from QB
    */
    public boolean getAllowUpdateItems() {
        return allowUpdateItems;
    }
    public boolean isAllowUpdateItems() {
        return getAllowUpdateItems();
    }
    public void setAllowUpdateItems(boolean newValue) {
        boolean old = allowUpdateItems;
        fireBeforePropertyChange(P_AllowUpdateItems, old, newValue);
        this.allowUpdateItems = newValue;
        firePropertyChange(P_AllowUpdateItems, old, this.allowUpdateItems);
    }

    @OAProperty(lowerName = "allowDisableItems", displayName = "Allow Disable Items", description = "ok to disable items that are not in quickbooks", displayLength = 5, uiColumnLength = 19)
    @OAColumn(name = "AllowDisableItems", sqlType = java.sql.Types.BOOLEAN)
    /**
      ok to disable items that are not in quickbooks
    */
    public boolean getAllowDisableItems() {
        return allowDisableItems;
    }
    public boolean isAllowDisableItems() {
        return getAllowDisableItems();
    }
    public void setAllowDisableItems(boolean newValue) {
        boolean old = allowDisableItems;
        fireBeforePropertyChange(P_AllowDisableItems, old, newValue);
        this.allowDisableItems = newValue;
        firePropertyChange(P_AllowDisableItems, old, this.allowDisableItems);
    }

    @OAProperty(lowerName = "allowUpdateCustomersNow", displayName = "Allow Update Customers Now", displayLength = 5, uiColumnLength = 26)
    @OAColumn(name = "AllowUpdateCustomersNow", sqlType = java.sql.Types.BOOLEAN)
    public boolean getAllowUpdateCustomersNow() {
        return allowUpdateCustomersNow;
    }
    public boolean isAllowUpdateCustomersNow() {
        return getAllowUpdateCustomersNow();
    }
    public void setAllowUpdateCustomersNow(boolean newValue) {
        boolean old = allowUpdateCustomersNow;
        fireBeforePropertyChange(P_AllowUpdateCustomersNow, old, newValue);
        this.allowUpdateCustomersNow = newValue;
        firePropertyChange(P_AllowUpdateCustomersNow, old, this.allowUpdateCustomersNow);
    }

    @OAProperty(lowerName = "allowUpdateItemsNow", displayName = "Allow Update Items Now", displayLength = 5, uiColumnLength = 22)
    @OAColumn(name = "AllowUpdateItemsNow", sqlType = java.sql.Types.BOOLEAN)
    public boolean getAllowUpdateItemsNow() {
        return allowUpdateItemsNow;
    }
    public boolean isAllowUpdateItemsNow() {
        return getAllowUpdateItemsNow();
    }
    public void setAllowUpdateItemsNow(boolean newValue) {
        boolean old = allowUpdateItemsNow;
        fireBeforePropertyChange(P_AllowUpdateItemsNow, old, newValue);
        this.allowUpdateItemsNow = newValue;
        firePropertyChange(P_AllowUpdateItemsNow, old, this.allowUpdateItemsNow);
    }

    @OAProperty(lowerName = "lastUpdated", displayName = "Last Updated", displayLength = 15, isProcessed = true, ignoreTimeZone = true)
    @OAColumn(name = "LastUpdated", sqlType = java.sql.Types.TIMESTAMP)
    public OADateTime getLastUpdated() {
        return lastUpdated;
    }
    public void setLastUpdated(OADateTime newValue) {
        OADateTime old = lastUpdated;
        fireBeforePropertyChange(P_LastUpdated, old, newValue);
        this.lastUpdated = newValue;
        firePropertyChange(P_LastUpdated, old, this.lastUpdated);
    }

    @OAProperty(lowerName = "lastGetOrders", displayName = "Last Get Orders", displayLength = 15, ignoreTimeZone = true)
    @OAColumn(name = "LastGetOrders", sqlType = java.sql.Types.TIMESTAMP)
    public OADateTime getLastGetOrders() {
        return lastGetOrders;
    }
    public void setLastGetOrders(OADateTime newValue) {
        OADateTime old = lastGetOrders;
        fireBeforePropertyChange(P_LastGetOrders, old, newValue);
        this.lastGetOrders = newValue;
        firePropertyChange(P_LastGetOrders, old, this.lastGetOrders);
    }

    @OAProperty(lowerName = "qbwcLastCalled", displayName = "Qbwc Last Called", displayLength = 15, uiColumnLength = 16, isProcessed = true, ignoreTimeZone = true)
    @OAColumn(name = "QbwcLastCalled", sqlType = java.sql.Types.TIMESTAMP)
    public OADateTime getQbwcLastCalled() {
        return qbwcLastCalled;
    }
    public void setQbwcLastCalled(OADateTime newValue) {
        OADateTime old = qbwcLastCalled;
        fireBeforePropertyChange(P_QbwcLastCalled, old, newValue);
        this.qbwcLastCalled = newValue;
        firePropertyChange(P_QbwcLastCalled, old, this.qbwcLastCalled);
    }

    @OAProperty(lowerName = "console", maxLength = 250, displayLength = 20, isProcessed = true)
    public String getConsole() {
        return console;
    }
    public void setConsole(String newValue) {
        String old = console;
        fireBeforePropertyChange(P_Console, old, newValue);
        this.console = newValue;
        firePropertyChange(P_Console, old, this.console);
    }

    @OAProperty(lowerName = "warningConsole", displayName = "Warning Console", maxLength = 250, displayLength = 20, isProcessed = true)
    public String getWarningConsole() {
        return warningConsole;
    }
    public void setWarningConsole(String newValue) {
        String old = warningConsole;
        fireBeforePropertyChange(P_WarningConsole, old, newValue);
        this.warningConsole = newValue;
        firePropertyChange(P_WarningConsole, old, this.warningConsole);
    }

    @OAProperty(lowerName = "qbwcConsole", displayName = "Qbwc Console", maxLength = 250, displayLength = 20, isProcessed = true)
    public String getQbwcConsole() {
        return qbwcConsole;
    }
    public void setQbwcConsole(String newValue) {
        String old = qbwcConsole;
        fireBeforePropertyChange(P_QbwcConsole, old, newValue);
        this.qbwcConsole = newValue;
        firePropertyChange(P_QbwcConsole, old, this.qbwcConsole);
    }

    @OAProperty(lowerName = "finerConsole", displayName = "Finer Console", maxLength = 250, displayLength = 20)
    public String getFinerConsole() {
        return finerConsole;
    }
    public void setFinerConsole(String newValue) {
        String old = finerConsole;
        fireBeforePropertyChange(P_FinerConsole, old, newValue);
        this.finerConsole = newValue;
        firePropertyChange(P_FinerConsole, old, this.finerConsole);
    }
    public void load(ResultSet rs, int id) throws SQLException {
        this.id = id;
        java.sql.Timestamp timestamp;
        timestamp = rs.getTimestamp(2);
        if (timestamp != null) this.started = new OADateTime(timestamp);
        this.enabled = (rs.getShort(3) == 1);
        OAObjectInfoDelegate.setPrimitiveNull(this, P_Enabled, rs.wasNull());
        this.currentStep = rs.getInt(4);
        timestamp = rs.getTimestamp(5);
        if (timestamp != null) this.tsCurrentStep = new OADateTime(timestamp);
        this.allowSendOrders = (rs.getShort(6) == 1);
        OAObjectInfoDelegate.setPrimitiveNull(this, P_AllowSendOrders, rs.wasNull());
        this.allowGetOrders = (rs.getShort(7) == 1);
        OAObjectInfoDelegate.setPrimitiveNull(this, P_AllowGetOrders, rs.wasNull());
        this.allowUpdateOrders = (rs.getShort(8) == 1);
        OAObjectInfoDelegate.setPrimitiveNull(this, P_AllowUpdateOrders, rs.wasNull());
        this.allowDisableOrders = (rs.getShort(9) == 1);
        OAObjectInfoDelegate.setPrimitiveNull(this, P_AllowDisableOrders, rs.wasNull());
        this.allowItemAdjustments = (rs.getShort(10) == 1);
        OAObjectInfoDelegate.setPrimitiveNull(this, P_AllowItemAdjustments, rs.wasNull());
        this.allowUpdateCustomers = (rs.getShort(11) == 1);
        OAObjectInfoDelegate.setPrimitiveNull(this, P_AllowUpdateCustomers, rs.wasNull());
        this.allowDisableCustomers = (rs.getShort(12) == 1);
        OAObjectInfoDelegate.setPrimitiveNull(this, P_AllowDisableCustomers, rs.wasNull());
        this.allowUpdateItems = (rs.getShort(13) == 1);
        OAObjectInfoDelegate.setPrimitiveNull(this, P_AllowUpdateItems, rs.wasNull());
        this.allowDisableItems = (rs.getShort(14) == 1);
        OAObjectInfoDelegate.setPrimitiveNull(this, P_AllowDisableItems, rs.wasNull());
        this.allowUpdateCustomersNow = (rs.getShort(15) == 1);
        OAObjectInfoDelegate.setPrimitiveNull(this, P_AllowUpdateCustomersNow, rs.wasNull());
        this.allowUpdateItemsNow = (rs.getShort(16) == 1);
        OAObjectInfoDelegate.setPrimitiveNull(this, P_AllowUpdateItemsNow, rs.wasNull());
        timestamp = rs.getTimestamp(17);
        if (timestamp != null) this.lastUpdated = new OADateTime(timestamp);
        timestamp = rs.getTimestamp(18);
        if (timestamp != null) this.lastGetOrders = new OADateTime(timestamp);
        timestamp = rs.getTimestamp(19);
        if (timestamp != null) this.qbwcLastCalled = new OADateTime(timestamp);

        this.changedFlag = false;
        this.newFlag = false;
    }
}
 
