// Generated by OABuilder
package com.cdi.model.oa;
 
import java.util.*;
import java.util.logging.*;
import java.sql.*;
import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.scheduler.*;
import com.viaoa.util.*;
import com.viaoa.annotation.*;
import com.cdi.delegate.oa.*;
import com.cdi.model.oa.filter.*;
import com.cdi.model.oa.propertypath.*;
 
@OAClass(
    lowerName = "texture",
    pluralName = "Textures",
    shortName = "tex",
    displayName = "Texture",
    isLookup = true,
    isPreSelect = true,
    displayProperty = "codeName",
    sortProperty = "code",
    noPojo = true
)
@OATable(
)
public class Texture extends OAObject {
    private static final long serialVersionUID = 1L;
    private static Logger LOG = Logger.getLogger(Texture.class.getName());

    public static final String P_Id = "id";
    public static final String P_Code = "code";
    public static final String P_Name = "name";
    public static final String P_Image = "image";
    public static final String P_Seq = "seq";
     
    public static final String P_CodeName = "codeName";
     
    public static final String P_Orders = "orders";
     
    protected volatile int id;
    protected volatile String code;
    protected volatile String name;
    protected volatile String image;
    protected volatile int seq;
     
     
    public Texture() {
        if (!isLoading()) setObjectDefaults();
    }
     
    public Texture(int id) {
        this();
        setId(id);
    }

    @OAProperty(lowerName = "id", isUnique = true, displayLength = 6)
    @OAId
    @OAColumn(name = "Id", sqlType = java.sql.Types.INTEGER)
    public int getId() {
        return id;
    }
    public void setId(int newValue) {
        int old = id;
        fireBeforePropertyChange(P_Id, old, newValue);
        this.id = newValue;
        firePropertyChange(P_Id, old, this.id);
    }

    @OAProperty(lowerName = "code", maxLength = 20, displayLength = 15)
    @OAColumn(name = "Code", maxLength = 20)
    public String getCode() {
        return code;
    }
    public void setCode(String newValue) {
        String old = code;
        fireBeforePropertyChange(P_Code, old, newValue);
        this.code = newValue;
        firePropertyChange(P_Code, old, this.code);
    }

    @OAProperty(lowerName = "name", maxLength = 50, displayLength = 20)
    @OAColumn(name = "Name", maxLength = 50)
    public String getName() {
        return name;
    }
    public void setName(String newValue) {
        String old = name;
        fireBeforePropertyChange(P_Name, old, newValue);
        this.name = newValue;
        firePropertyChange(P_Name, old, this.name);
    }

    @OAProperty(lowerName = "image", maxLength = 75, displayLength = 20, uiColumnLength = 12)
    @OAColumn(name = "Image", maxLength = 75)
    public String getImage() {
        return image;
    }
    public void setImage(String newValue) {
        String old = image;
        fireBeforePropertyChange(P_Image, old, newValue);
        this.image = newValue;
        firePropertyChange(P_Image, old, this.image);
    }

    @OAProperty(lowerName = "seq", trackPrimitiveNull = false, displayLength = 6, isAutoSeq = true)
    @OAColumn(name = "Seq", sqlType = java.sql.Types.INTEGER)
    public int getSeq() {
        return seq;
    }
    public void setSeq(int newValue) {
        int old = seq;
        fireBeforePropertyChange(P_Seq, old, newValue);
        this.seq = newValue;
        firePropertyChange(P_Seq, old, this.seq);
    }
    @OACalculatedProperty(displayName = "Display", displayLength = 20, columnLength = 15, properties = {P_Code, P_Name})
    public String getCodeName() {
        String s = code;
        if (s == null) s += "";
        if (name != null) s += " - " + name;    
        return s;
    }

    @OAMany(
        toClass = Order.class, 
        reverseName = Order.P_Texture, 
        createMethod = false
    )
    private Hub<Order> getOrders() {
        // oamodel has createMethod set to false, this method exists only for annotations.
        return null;
    }
    public void load(ResultSet rs, int id) throws SQLException {
        this.id = id;
        this.code = rs.getString(2);
        this.name = rs.getString(3);
        this.image = rs.getString(4);
        this.seq = rs.getInt(5);

        this.changedFlag = false;
        this.newFlag = false;
    }
}
 
